from django.urls import path
from .views import (
    BednyListView,
    dashboard_bedny_view,
    dashboard_kamiony_view,
    dashboard_vyroba_view,
    dashboard_vyroba_historie_view,
    dashboard_vyroba_historie_mesic_view,
    dashboard_vyroba_zakaznici_vyuziti_view,
    dashboard_bedny_k_navezeni_view,
    dashboard_bedny_k_navezeni_pdf_view,
    dashboard_bedny_k_navezeni_poznamka_view,
    dashboard_bedny_k_navezeni_poznamka_pozice_view,
    dashboard_bedny_k_navezeni_nasledne_view,
    protokol_kamion_vydej_pdf_view,
    dodaci_list_kamion_vydej_pdf_view,
    proforma_kamion_vydej_pdf_view,
    bedna_scan_view,
    bedna_scan_navezeni_view,
    bedna_scan_zkontrolovano_view,
    bedna_scan_pohyb_view,
    sarze_scan_view,
    sarze_scan_presunout_view,
    sarze_scan_change_krok_view,
    bedna_skener_view,
    rychle_zalozeni_sarze_view,
    rychle_zalozeni_sarze_posledni_prehled_view,
    rychle_zalozeni_sarze_patro_view,
    rychle_zalozeni_sarze_prehled_view,
    rychle_zalozeni_sarze_tisk_view,
    rychle_zalozeni_sarze_upravit_view,
)

urlpatterns = [
    path('dashboard/bedny/', dashboard_bedny_view, name='dashboard_bedny'),
    path('dashboard/kamiony/', dashboard_kamiony_view, name='dashboard_kamiony'),    
    path('dashboard/vyroba/', dashboard_vyroba_view, name='dashboard_vyroba'),
    path('dashboard/vyroba/historie/', dashboard_vyroba_historie_view, name='dashboard_vyroba_historie'),
    path('dashboard/vyroba/historie/mesic/', dashboard_vyroba_historie_mesic_view, name='dashboard_vyroba_historie_mesic'),
    path('dashboard/vyroba/zakaznici-vyuziti/', dashboard_vyroba_zakaznici_vyuziti_view, name='dashboard_vyroba_zakaznici_vyuziti'),
    path('bedny/', BednyListView.as_view(), name='bedny_list'),
    path('bedny/scan/<int:cislo_bedny>/', bedna_scan_view, name='bedna_scan'),
    path('bedny/scan/<int:cislo_bedny>/navezeni/', bedna_scan_navezeni_view, name='bedna_scan_navezeni'),
    path('bedny/scan/<int:cislo_bedny>/zkontrolovano/', bedna_scan_zkontrolovano_view, name='bedna_scan_zkontrolovano'),
    path('bedny/scan/<int:cislo_bedny>/pohyb/', bedna_scan_pohyb_view, name='bedna_scan_pohyb'),
    path('sarze/scan/<int:cislo_sarze>/', sarze_scan_view, name='sarze_scan'),
    path(
        'sarze/scan/<int:cislo_sarze>/krok/<int:krok_id>/presunout/',
        sarze_scan_presunout_view,
        name='sarze_scan_presunout',
    ),
    path(
        'sarze/scan/<int:cislo_sarze>/krok/<int:krok_id>/upravit/',
        sarze_scan_change_krok_view,
        name='sarze_scan_change_krok',
    ),
    path('bedny/skener/', bedna_skener_view, name='bedna_skener'),
    path('sarze/rychle-zalozeni/', rychle_zalozeni_sarze_view, name='rychle_zalozeni_sarze'),
    path(
        'sarze/rychle-zalozeni/posledni-prehled/',
        rychle_zalozeni_sarze_posledni_prehled_view,
        name='rychle_zalozeni_sarze_posledni_prehled',
    ),
    path(
        'sarze/rychle-zalozeni/krok/<int:krok_id>/patro/<int:patro>/',
        rychle_zalozeni_sarze_patro_view,
        name='rychle_zalozeni_sarze_patro',
    ),
    path(
        'sarze/rychle-zalozeni/krok/<int:krok_id>/prehled/',
        rychle_zalozeni_sarze_prehled_view,
        name='rychle_zalozeni_sarze_prehled',
    ),
    path(
        'sarze/rychle-zalozeni/krok/<int:krok_id>/tisk/',
        rychle_zalozeni_sarze_tisk_view,
        name='rychle_zalozeni_sarze_tisk',
    ),
    path('sarze/rychle-zalozeni/krok/<int:krok_id>/upravit/',
         rychle_zalozeni_sarze_upravit_view,
         name='rychle_zalozeni_sarze_upravit',
    ),
    path('bedny/k-navezeni/', dashboard_bedny_k_navezeni_view, name='dashboard_bedny_k_navezeni'),
    path('bedny/k-navezeni/poznamka/', dashboard_bedny_k_navezeni_poznamka_view, name='dashboard_bedny_k_navezeni_poznamka'),
    path('bedny/k-navezeni/pozice-poznamka/', dashboard_bedny_k_navezeni_poznamka_pozice_view, name='dashboard_bedny_k_navezeni_pozice_poznamka'),
    path('bedny/k-navezeni/nasledne/', dashboard_bedny_k_navezeni_nasledne_view, name='dashboard_bedny_k_navezeni_nasledne'),
    path('bedny/k-navezeni/pdf/', dashboard_bedny_k_navezeni_pdf_view, name='dashboard_bedny_k_navezeni_pdf'),
    path('protokol/kamion-vydej/<int:pk>/', protokol_kamion_vydej_pdf_view, name='protokol_kamion_vydej_pdf'),
    path('dodaci-list/kamion-vydej/<int:pk>/', dodaci_list_kamion_vydej_pdf_view, name='dodaci_list_kamion_vydej_pdf'),
    path('proforma/kamion-vydej/<int:pk>/', proforma_kamion_vydej_pdf_view, name='proforma_kamion_vydej_pdf'),
]
