from django.urls import path
from .views import (
    BednyListView,
    dashboard_bedny_view,
    dashboard_kamiony_view,
    dashboard_vyroba_view,
    dashboard_vyroba_historie_view,
    dashboard_vyroba_historie_mesic_view,
    dashboard_bedny_k_navezeni_view,
    dashboard_bedny_k_navezeni_pdf_view,
    dashboard_bedny_k_navezeni_poznamka_view,
    dashboard_bedny_k_navezeni_poznamka_pozice_view,
    dashboard_bedny_k_navezeni_nasledne_view,
    protokol_kamion_vydej_pdf_view,
    dodaci_list_kamion_vydej_pdf_view,
    proforma_kamion_vydej_pdf_view,
    rychle_zalozeni_sarze_view,
)

urlpatterns = [
    path('dashboard/bedny/', dashboard_bedny_view, name='dashboard_bedny'),
    path('dashboard/kamiony/', dashboard_kamiony_view, name='dashboard_kamiony'),    
    path('dashboard/vyroba/', dashboard_vyroba_view, name='dashboard_vyroba'),
    path('dashboard/vyroba/historie/', dashboard_vyroba_historie_view, name='dashboard_vyroba_historie'),
    path('dashboard/vyroba/historie/mesic/', dashboard_vyroba_historie_mesic_view, name='dashboard_vyroba_historie_mesic'),
    path('bedny/', BednyListView.as_view(), name='bedny_list'),
    path('sarze/rychle-zalozeni/', rychle_zalozeni_sarze_view, name='rychle_zalozeni_sarze'),
    path('bedny/k-navezeni/', dashboard_bedny_k_navezeni_view, name='dashboard_bedny_k_navezeni'),
    path('bedny/k-navezeni/poznamka/', dashboard_bedny_k_navezeni_poznamka_view, name='dashboard_bedny_k_navezeni_poznamka'),
    path('bedny/k-navezeni/pozice-poznamka/', dashboard_bedny_k_navezeni_poznamka_pozice_view, name='dashboard_bedny_k_navezeni_pozice_poznamka'),
    path('bedny/k-navezeni/nasledne/', dashboard_bedny_k_navezeni_nasledne_view, name='dashboard_bedny_k_navezeni_nasledne'),
    path('bedny/k-navezeni/pdf/', dashboard_bedny_k_navezeni_pdf_view, name='dashboard_bedny_k_navezeni_pdf'),
    path('protokol/kamion-vydej/<int:pk>/', protokol_kamion_vydej_pdf_view, name='protokol_kamion_vydej_pdf'),
    path('dodaci-list/kamion-vydej/<int:pk>/', dodaci_list_kamion_vydej_pdf_view, name='dodaci_list_kamion_vydej_pdf'),
    path('proforma/kamion-vydej/<int:pk>/', proforma_kamion_vydej_pdf_view, name='proforma_kamion_vydej_pdf'),
]
