# Generated by Django 5.2.1 on 2025-05-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Kamión',
                'verbose_name_plural': 'Kamióny',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Zakazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikl', models.CharField(max_length=100, verbose_name='Artikl')),
                ('prumer', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Průměr')),
                ('delka', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Délka')),
                ('predpis', models.CharField(max_length=100, verbose_name='Předpis')),
                ('typ_hlavy', models.CharField(choices=[('TK', 'TK'), ('SK', 'SK'), ('ZK', 'ZK')], max_length=3, verbose_name='Typ hlavy')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název')),
                ('komplet', models.BooleanField(default=False, verbose_name='Kompletní?')),
                ('kamion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazky', to='orders.kamion')),
            ],
            options={
                'verbose_name': 'Zakázka',
                'verbose_name_plural': 'Zakázky',
                'ordering': ['-kamion_id__id'],
            },
        ),
        migrations.CreateModel(
            name='Bedna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_bedny', models.CharField(max_length=50, verbose_name='Číslo bedny')),
                ('material', models.CharField(max_length=50, verbose_name='Materiál')),
                ('sarze', models.CharField(max_length=50, verbose_name='Šarže')),
                ('tryskat', models.BooleanField(default=False, verbose_name='K tryskání')),
                ('rovnat', models.BooleanField(default=False, verbose_name='K rovnání')),
                ('poznamka', models.CharField(max_length=100, verbose_name='Poznámka')),
                ('stav_bedny', models.CharField(choices=[('TK', 'TK'), ('SK', 'SK'), ('ZK', 'ZK')], max_length=2, verbose_name='Stav bedny')),
                ('zakazka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedny', to='orders.zakazka')),
            ],
            options={
                'verbose_name': 'Bedna',
                'verbose_name_plural': 'Bedny',
                'ordering': ['zakazka_id__id'],
            },
        ),
        migrations.AddField(
            model_name='kamion',
            name='zakaznik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kamiony', to='orders.zakaznik'),
        ),
    ]
