# Generated by Django 5.2.1 on 2025-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='poznamka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KR', 'Křivá'), ('VY', 'Vyrovnaná'), ('TR', 'K tryskání'), ('OT', 'Otryskaná'), ('KE', 'K expedici'), ('EX', 'Expedováno')], max_length=2, verbose_name='Stav bedny'),
        ),
    ]
