# Generated by Django 5.2.1 on 2025-05-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_bedna_poznamka_alter_bedna_stav_bedny'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='zkratka',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Zkratka'),
            preserve_default=False,
        ),
    ]
