# Generated by Django 5.2.1 on 2025-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_zakaznik_zkratka"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedna",
            name="hmotnost",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=5, verbose_name="Hmotnost"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zakazka",
            name="hmotnost_zakazky",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=6,
                verbose_name="Hmotnost zakázky",
            ),
            preserve_default=False,
        ),
    ]
