# Generated by Django 5.2.1 on 2025-05-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_bedna_hmotnost_zakazka_hmotnost_zakazky"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zakazka",
            name="hmotnost_zakazky",
        ),
    ]
