# Generated by Django 5.2.1 on 2025-05-18 08:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_zakazka_hmotnost_zakazky"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBedna",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cislo_bedny",
                    models.CharField(max_length=50, verbose_name="Číslo bedny"),
                ),
                (
                    "hmotnost",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Hmotnost"
                    ),
                ),
                ("material", models.CharField(max_length=50, verbose_name="Materiál")),
                ("sarze", models.CharField(max_length=50, verbose_name="Šarže")),
                (
                    "tryskat",
                    models.BooleanField(default=False, verbose_name="K tryskání"),
                ),
                (
                    "rovnat",
                    models.BooleanField(default=False, verbose_name="K rovnání"),
                ),
                (
                    "poznamka",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Poznámka"
                    ),
                ),
                (
                    "stav_bedny",
                    models.CharField(
                        choices=[
                            ("PR", "Přijato"),
                            ("NA", "Navezeno"),
                            ("DZ", "Do zpracování"),
                            ("ZA", "Zakaleno"),
                            ("ZK", "Zkontrolováno"),
                            ("KR", "Křivá"),
                            ("VY", "Vyrovnaná"),
                            ("TR", "K tryskání"),
                            ("OT", "Otryskaná"),
                            ("KE", "K expedici"),
                            ("EX", "Expedováno"),
                        ],
                        max_length=2,
                        verbose_name="Stav bedny",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zakazka_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.zakazka",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bedna",
                "verbose_name_plural": "historical Bedny",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKamion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("datum", models.DateField(verbose_name="Datum")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zakaznik_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.zakaznik",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kamión",
                "verbose_name_plural": "historical Kamióny",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalZakazka",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("artikl", models.CharField(max_length=100, verbose_name="Artikl")),
                (
                    "prumer",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Průměr"
                    ),
                ),
                (
                    "delka",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="Délka"
                    ),
                ),
                ("predpis", models.CharField(max_length=100, verbose_name="Předpis")),
                (
                    "typ_hlavy",
                    models.CharField(
                        choices=[("TK", "TK"), ("SK", "SK"), ("ZK", "ZK")],
                        max_length=3,
                        verbose_name="Typ hlavy",
                    ),
                ),
                ("nazev", models.CharField(max_length=100, verbose_name="Název")),
                (
                    "komplet",
                    models.BooleanField(default=False, verbose_name="Kompletní?"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kamion_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.kamion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Zakázka",
                "verbose_name_plural": "historical Zakázky",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalZakaznik",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nazev", models.CharField(max_length=100)),
                ("zkratka", models.CharField(max_length=3, verbose_name="Zkratka")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Zákazník",
                "verbose_name_plural": "historical Zákazníci",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
