# Generated by Django 5.2.1 on 2025-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_historicalbedna_historicalkamion_historicalzakazka_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedna",
            options={
                "ordering": ["id"],
                "verbose_name": "Bedna",
                "verbose_name_plural": "Bedny",
            },
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="adresa",
            field=models.CharField(max_length=100, null=True, verbose_name="Adresa"),
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="cislo_DL",
            field=models.CharField(
                default=135.0, max_length=50, verbose_name="Číslo DL"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="email",
            field=models.EmailField(max_length=100, null=True, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="kontaktni_osoba",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Kontaktní osoba"
            ),
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="mesto",
            field=models.CharField(max_length=50, null=True, verbose_name="Město"),
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="stat",
            field=models.CharField(max_length=50, null=True, verbose_name="Stát"),
        ),
        migrations.AddField(
            model_name="historicalzakaznik",
            name="telefon",
            field=models.CharField(max_length=50, null=True, verbose_name="Telefon"),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="adresa",
            field=models.CharField(max_length=100, null=True, verbose_name="Adresa"),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="cislo_DL",
            field=models.CharField(
                default="2025/125", max_length=50, verbose_name="Číslo DL"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="email",
            field=models.EmailField(max_length=100, null=True, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="kontaktni_osoba",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Kontaktní osoba"
            ),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="mesto",
            field=models.CharField(max_length=50, null=True, verbose_name="Město"),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="stat",
            field=models.CharField(max_length=50, null=True, verbose_name="Stát"),
        ),
        migrations.AddField(
            model_name="zakaznik",
            name="telefon",
            field=models.CharField(max_length=50, null=True, verbose_name="Telefon"),
        ),
    ]
