# Generated by Django 5.2.1 on 2025-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_bedna_options_historicalzakaznik_adresa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalzakaznik",
            name="cislo_DL",
        ),
        migrations.RemoveField(
            model_name="zakaznik",
            name="cislo_DL",
        ),
        migrations.AddField(
            model_name="historicalkamion",
            name="cislo_dl",
            field=models.CharField(
                default="2025/121", max_length=50, verbose_name="Číslo DL"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kamion",
            name="cislo_dl",
            field=models.CharField(
                default="2025/121", max_length=50, verbose_name="Číslo DL"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="adresa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Adresa"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="kontaktni_osoba",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Kontaktní osoba"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="mesto",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Město"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="stat",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Stát"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="telefon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="adresa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Adresa"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="kontaktni_osoba",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Kontaktní osoba"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="mesto",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Město"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="stat",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Stát"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="telefon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefon"
            ),
        ),
    ]
