# Generated by Django 5.2.1 on 2025-05-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_historicalzakaznik_cislo_dl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kamion",
            options={
                "ordering": ["id"],
                "verbose_name": "Kamión",
                "verbose_name_plural": "Kamióny",
            },
        ),
        migrations.AlterModelOptions(
            name="zakazka",
            options={
                "ordering": ["id"],
                "verbose_name": "Zakázka",
                "verbose_name_plural": "Zakázky",
            },
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="priorita",
            field=models.CharField(
                choices=[
                    ("STAN", "Standardní"),
                    ("P2", "Priorita P2"),
                    ("P1", "Priorita P1"),
                ],
                default="STAN",
                max_length=5,
                verbose_name="Priorita",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zakazka",
            name="priorita",
            field=models.CharField(
                choices=[
                    ("STAN", "Standardní"),
                    ("P2", "Priorita P2"),
                    ("P1", "Priorita P1"),
                ],
                default="STAN",
                max_length=5,
                verbose_name="Priorita",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalzakazka",
            name="kamion_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.kamion",
                verbose_name="Kamión",
            ),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="kamion_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zakazky",
                to="orders.kamion",
                verbose_name="Kamión",
            ),
        ),
    ]
