# Generated by Django 5.2.1 on 2025-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_historicalzakazka_priorita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalzakazka",
            name="expedovano",
            field=models.BooleanField(default=False, verbose_name="Expedováno"),
        ),
        migrations.AddField(
            model_name="zakazka",
            name="expedovano",
            field=models.BooleanField(default=False, verbose_name="Expedováno"),
        ),
    ]
