# Generated by Django 5.2.1 on 2025-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_historicalzakazka_expedovano_zakazka_expedovano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzakazka",
            name="komplet",
            field=models.BooleanField(default=False, verbose_name="Kompletní"),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="komplet",
            field=models.BooleanField(default=False, verbose_name="Kompletní"),
        ),
    ]
