# Generated by Django 5.2.1 on 2025-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_historicalzakazka_komplet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalzakazka",
            name="nazev",
        ),
        migrations.RemoveField(
            model_name="zakazka",
            name="nazev",
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="popis",
            field=models.CharField(default="-", max_length=100, verbose_name="Popis"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zakazka",
            name="popis",
            field=models.CharField(default="-", max_length=100, verbose_name="Popis"),
            preserve_default=False,
        ),
    ]
