# Generated by Django 5.2.1 on 2025-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_remove_historicalzakazka_nazev_remove_zakazka_nazev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedna",
            name="dodavatel_materialu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Dod.mat."
            ),
        ),
        migrations.AddField(
            model_name="bedna",
            name="operator",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Bediener"
            ),
        ),
        migrations.AddField(
            model_name="bedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Tára",
            ),
        ),
        migrations.AddField(
            model_name="bedna",
            name="vyrobni_zakazka",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Fert.-auf. Nr."
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="dodavatel_materialu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Dod.mat."
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="operator",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Bediener"
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Tára",
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="vyrobni_zakazka",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Fert.-auf. Nr."
            ),
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="povrch",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Povrch"
            ),
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="prubeh",
            field=models.IntegerField(blank=True, null=True, verbose_name="Vorgang"),
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva"
            ),
        ),
        migrations.AddField(
            model_name="zakazka",
            name="povrch",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Povrch"
            ),
        ),
        migrations.AddField(
            model_name="zakazka",
            name="prubeh",
            field=models.IntegerField(blank=True, null=True, verbose_name="Vorgang"),
        ),
        migrations.AddField(
            model_name="zakazka",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva"
            ),
        ),
        migrations.AlterField(
            model_name="bedna",
            name="hmotnost",
            field=models.DecimalField(
                decimal_places=1, max_digits=5, verbose_name="Hm. netto"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="hmotnost",
            field=models.DecimalField(
                decimal_places=1, max_digits=5, verbose_name="Hm. netto"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakazka",
            name="artikl",
            field=models.CharField(max_length=50, verbose_name="Artikl"),
        ),
        migrations.AlterField(
            model_name="historicalzakazka",
            name="predpis",
            field=models.CharField(max_length=30, verbose_name="Předpis/výkres"),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="artikl",
            field=models.CharField(max_length=50, verbose_name="Artikl"),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="predpis",
            field=models.CharField(max_length=30, verbose_name="Předpis/výkres"),
        ),
    ]
