# Generated by Django 5.2.1 on 2025-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_bedna_dodavatel_materialu_bedna_operator_bedna_tara_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny/-en'},
        ),
        migrations.AlterModelOptions(
            name='historicalbedna',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bedna', 'verbose_name_plural': 'historical bedny/-en'},
        ),
        migrations.AlterModelOptions(
            name='historicalkamion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Kamión', 'verbose_name_plural': 'historical kamióny/-ů'},
        ),
        migrations.AlterModelOptions(
            name='historicalzakazka',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zakázka', 'verbose_name_plural': 'historical zakázky/-ek'},
        ),
        migrations.AlterModelOptions(
            name='historicalzakaznik',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zákazník', 'verbose_name_plural': 'historical zákazníci(-ků)'},
        ),
        migrations.AlterModelOptions(
            name='kamion',
            options={'ordering': ['id'], 'verbose_name': 'Kamión', 'verbose_name_plural': 'kamióny/-ů'},
        ),
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky/-ek'},
        ),
        migrations.AlterModelOptions(
            name='zakaznik',
            options={'ordering': ['nazev'], 'verbose_name': 'Zákazník', 'verbose_name_plural': 'zákazníci(-ků)'},
        ),
        migrations.AddField(
            model_name='bedna',
            name='datum_expedice',
            field=models.DateField(blank=True, null=True, verbose_name='Datum expedice'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='datum_expedice',
            field=models.DateField(blank=True, null=True, verbose_name='Datum expedice'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='cislo_bedny',
            field=models.CharField(max_length=20, verbose_name='Číslo bedny'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='dodavatel_materialu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dod.mat.'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='material',
            field=models.CharField(max_length=20, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bediener'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='sarze',
            field=models.CharField(max_length=20, verbose_name='Šarže'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KR', 'Křivá'), ('VY', 'Vyrovnaná'), ('TR', 'K tryskání'), ('OT', 'Otryskaná'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fert.-auf. Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='cislo_bedny',
            field=models.CharField(max_length=20, verbose_name='Číslo bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='dodavatel_materialu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dod.mat.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='material',
            field=models.CharField(max_length=20, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bediener'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='sarze',
            field=models.CharField(max_length=20, verbose_name='Šarže'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KR', 'Křivá'), ('VY', 'Vyrovnaná'), ('TR', 'K tryskání'), ('OT', 'Otryskaná'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fert.-auf. Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='povrch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Oberfläche'),
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='priorita',
            field=models.CharField(choices=[('-', 'Nízká'), ('P2', 'Střední P2'), ('P1', 'Vysoká P1')], default='-', max_length=5, verbose_name='Priorita'),
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='vrstva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Beschichtung'),
        ),
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='zkratka',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Zkratka'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='povrch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Oberfläche'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='priorita',
            field=models.CharField(choices=[('-', 'Nízká'), ('P2', 'Střední P2'), ('P1', 'Vysoká P1')], default='-', max_length=5, verbose_name='Priorita'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='vrstva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Beschichtung'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='zkratka',
            field=models.CharField(max_length=3, unique=True, verbose_name='Zkratka'),
        ),
    ]
