# Generated by Django 5.2.1 on 2025-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_bedna_options_alter_historicalbedna_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=65.0,
                max_digits=5,
                null=True,
                verbose_name="Tára",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=65.0,
                max_digits=5,
                null=True,
                verbose_name="Tára",
            ),
        ),
    ]
