# Generated by Django 5.2.1 on 2025-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_bedna_tara_alter_historicalbedna_tara'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
        migrations.AlterModelOptions(
            name='historicalbedna',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bedna', 'verbose_name_plural': 'historical bedny'},
        ),
        migrations.AlterModelOptions(
            name='historicalkamion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Kamión', 'verbose_name_plural': 'historical kamióny'},
        ),
        migrations.AlterModelOptions(
            name='historicalzakazka',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zakázka', 'verbose_name_plural': 'historical zakázky'},
        ),
        migrations.AlterModelOptions(
            name='historicalzakaznik',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zákazník', 'verbose_name_plural': 'historical zákazníci'},
        ),
        migrations.AlterModelOptions(
            name='kamion',
            options={'ordering': ['id'], 'verbose_name': 'Kamión', 'verbose_name_plural': 'kamióny'},
        ),
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky'},
        ),
        migrations.AlterModelOptions(
            name='zakaznik',
            options={'ordering': ['nazev'], 'verbose_name': 'Zákazník', 'verbose_name_plural': 'zákazníci'},
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='zinkovna',
            field=models.CharField(blank=True, choices=[('HUBER', 'Huber'), ('STIEFLER', 'Stiefler'), ('SULZ', 'Sulz')], max_length=10, null=True, verbose_name='Zinkovna'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='zinkovna',
            field=models.CharField(blank=True, choices=[('HUBER', 'Huber'), ('STIEFLER', 'Stiefler'), ('SULZ', 'Sulz')], max_length=10, null=True, verbose_name='Zinkovna'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='dodavatel_materialu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lief.'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='sarze',
            field=models.CharField(max_length=20, verbose_name='Šarže materiálu'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='tara',
            field=models.DecimalField(decimal_places=1, default=65.0, max_digits=5, verbose_name='Tára'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fertigungs-auftrags Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='dodavatel_materialu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lief.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='sarze',
            field=models.CharField(max_length=20, verbose_name='Šarže materiálu'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='tara',
            field=models.DecimalField(decimal_places=1, default=65.0, max_digits=5, verbose_name='Tára'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fertigungs-auftrags Nr.'),
        ),
    ]
