# Generated by Django 5.2.1 on 2025-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_bedna_options_alter_historicalbedna_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Hm. netto'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže materiálu'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Hm. netto'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže materiálu'),
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='artikl',
            field=models.CharField(max_length=50, verbose_name='Artikl / Zakázka (Charge)'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='artikl',
            field=models.CharField(max_length=50, verbose_name='Artikl / Zakázka (Charge)'),
        ),
    ]
