# Generated by Django 5.2.1 on 2025-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_bedna_hmotnost_alter_bedna_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='cisla_beden_auto',
            field=models.BooleanField(default=False, verbose_name='Č. beden automaticky'),
        ),
        migrations.AddField(
            model_name='historicalzakaznik',
            name='vse_tryskat',
            field=models.BooleanField(default=False, verbose_name='Všechny bedny tryskat'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='cisla_beden_auto',
            field=models.BooleanField(default=False, verbose_name='Č. beden automaticky'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='vse_tryskat',
            field=models.BooleanField(default=False, verbose_name='Všechny bedny tryskat'),
        ),
    ]
