# Generated by Django 5.2.1 on 2025-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_historicalzakaznik_cisla_beden_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='cislo_bedny',
            field=models.PositiveIntegerField(verbose_name='Číslo bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='cislo_bedny',
            field=models.PositiveIntegerField(verbose_name='Číslo bedny'),
        ),
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='cisla_beden_auto',
            field=models.BooleanField(default=False, verbose_name='Čísla beden automaticky'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='cisla_beden_auto',
            field=models.BooleanField(default=False, verbose_name='Čísla beden automaticky'),
        ),
    ]
