# Generated by Django 5.2.1 on 2025-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_bedna_cislo_bedny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='tara',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tára'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='tara',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tára'),
        ),
    ]
