# Generated by Django 5.2.1 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_bedna_tara_alter_historicalbedna_tara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Tára'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Tára'),
        ),
    ]
