# Generated by Django 5.2.1 on 2025-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_bedna_tara_alter_historicalbedna_tara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='cislo_bedny',
            field=models.PositiveIntegerField(blank=True, verbose_name='Číslo bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='cislo_bedny',
            field=models.PositiveIntegerField(blank=True, verbose_name='Číslo bedny'),
        ),
    ]
