# Generated by Django 5.2.1 on 2025-05-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_alter_historicalzakaznik_nazev_alter_zakaznik_nazev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="zakazka_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bedny",
                to="orders.zakazka",
                verbose_name="Zakázka",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="zakazka_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.zakazka",
                verbose_name="Zakázka",
            ),
        ),
        migrations.AlterField(
            model_name="historicalkamion",
            name="zakaznik_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.zakaznik",
                verbose_name="Zákazník",
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="nazev",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Název zákazníka"
            ),
        ),
        migrations.AlterField(
            model_name="kamion",
            name="zakaznik_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kamiony",
                to="orders.zakaznik",
                verbose_name="Zákazník",
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="nazev",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Název zákazníka"
            ),
        ),
    ]
