# Generated by Django 5.2.1 on 2025-05-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_alter_bedna_zakazka_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bedna",
            name="datum_expedice",
        ),
        migrations.RemoveField(
            model_name="historicalbedna",
            name="datum_expedice",
        ),
        migrations.RemoveField(
            model_name="historicalzakazka",
            name="kamion_id",
        ),
        migrations.RemoveField(
            model_name="zakazka",
            name="kamion_id",
        ),
        migrations.AddField(
            model_name="historicalkamion",
            name="prijem_vydej",
            field=models.CharField(
                choices=[("P", "Přijem"), ("V", "Výdej")],
                default="P",
                max_length=1,
                verbose_name="Přijem/Výdej",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="kamion_prijem_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.kamion",
                verbose_name="Kamión příjem",
            ),
        ),
        migrations.AddField(
            model_name="historicalzakazka",
            name="kamion_vydej_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.kamion",
                verbose_name="Kamión výdej",
            ),
        ),
        migrations.AddField(
            model_name="kamion",
            name="prijem_vydej",
            field=models.CharField(
                choices=[("P", "Přijem"), ("V", "Výdej")],
                default="P",
                max_length=1,
                verbose_name="Přijem/Výdej",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zakazka",
            name="kamion_prijem_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zakazky_prijem",
                to="orders.kamion",
                verbose_name="Kamión příjem",
            ),
        ),
        migrations.AddField(
            model_name="zakazka",
            name="kamion_vydej_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zakazky_vydej",
                to="orders.kamion",
                verbose_name="Kamión výdej",
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakazka",
            name="artikl",
            field=models.CharField(max_length=50, verbose_name="Artikl / Zakázka"),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="artikl",
            field=models.CharField(max_length=50, verbose_name="Artikl / Zakázka"),
        ),
    ]
