# Generated by Django 5.2.1 on 2025-05-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_remove_bedna_datum_expedice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zakazka",
            name="kamion_prijem_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zakazky_prijem",
                to="orders.kamion",
                verbose_name="Kamión příjem",
            ),
        ),
    ]
