# Generated by Django 5.2.1 on 2025-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_alter_zakazka_kamion_prijem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="cisla_beden_auto",
            field=models.BooleanField(
                default=False, verbose_name="Č. beden automaticky"
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="vse_tryskat",
            field=models.BooleanField(default=False, verbose_name="Vše tryskat"),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="cisla_beden_auto",
            field=models.BooleanField(
                default=False, verbose_name="Č. beden automaticky"
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="vse_tryskat",
            field=models.BooleanField(default=False, verbose_name="Vše tryskat"),
        ),
    ]
