# Generated by Django 5.2.1 on 2025-05-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_historicalzakaznik_cisla_beden_auto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalkamion",
            name="cislo_dl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Číslo DL"
            ),
        ),
        migrations.AlterField(
            model_name="kamion",
            name="cislo_dl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Číslo DL"
            ),
        ),
    ]
