# Generated by Django 5.2.1 on 2025-05-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_alter_historicalkamion_cislo_dl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zakazka",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("change_expedovana_zakazka", "Může měnit expedované zakázky")
                ],
                "verbose_name": "Zakázka",
                "verbose_name_plural": "zakázky",
            },
        ),
    ]
