# Generated by Django 5.2.1 on 2025-05-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_zakazka_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='rovnat',
            field=models.CharField(blank=True, choices=[('RO', 'Rovná'), ('KR', 'Křivá'), ('VY', 'Vyrovnaná')], default=None, max_length=5, null=True, verbose_name='Rovnání'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='tryskat',
            field=models.CharField(blank=True, choices=[('CI', 'Čistá'), ('SP', 'Špinavá'), ('OT', 'Otryskaná')], default=None, max_length=5, null=True, verbose_name='Tryskání'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='rovnat',
            field=models.CharField(blank=True, choices=[('RO', 'Rovná'), ('KR', 'Křivá'), ('VY', 'Vyrovnaná')], default=None, max_length=5, null=True, verbose_name='Rovnání'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='tryskat',
            field=models.CharField(blank=True, choices=[('CI', 'Čistá'), ('SP', 'Špinavá'), ('OT', 'Otryskaná')], default=None, max_length=5, null=True, verbose_name='Tryskání'),
        ),
    ]
