# Generated by Django 5.2.1 on 2025-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_bedna_rovnat_alter_bedna_stav_bedny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='stav_bedny',
            field=models.CharField(choices=[('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='PR', max_length=2, verbose_name='Stav bedny'),
        ),
    ]
