# Generated by Django 5.2.1 on 2025-05-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_historicalkamion_místo_expedice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkamion',
            old_name='místo_expedice',
            new_name='misto_expedice',
        ),
        migrations.RenameField(
            model_name='kamion',
            old_name='místo_expedice',
            new_name='misto_expedice',
        ),
    ]
