# Generated by Django 5.2.1 on 2025-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0034_rename_místo_expedice_historicalkamion_misto_expedice_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="rovnat",
            field=models.CharField(
                choices=[
                    ("", "--------"),
                    ("RO", "Rovná"),
                    ("KR", "Křivá"),
                    ("VY", "Vyrovnaná"),
                ],
                default="",
                max_length=5,
                verbose_name="Rovnání",
            ),
        ),
        migrations.AlterField(
            model_name="bedna",
            name="tryskat",
            field=models.CharField(
                choices=[
                    ("", "--------"),
                    ("CI", "Čistá"),
                    ("SP", "Špinavá"),
                    ("OT", "Otryskaná"),
                ],
                default="",
                max_length=5,
                verbose_name="Tryskání",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="rovnat",
            field=models.CharField(
                choices=[
                    ("", "--------"),
                    ("RO", "Rovná"),
                    ("KR", "Křivá"),
                    ("VY", "Vyrovnaná"),
                ],
                default="",
                max_length=5,
                verbose_name="Rovnání",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="tryskat",
            field=models.CharField(
                choices=[
                    ("", "--------"),
                    ("CI", "Čistá"),
                    ("SP", "Špinavá"),
                    ("OT", "Otryskaná"),
                ],
                default="",
                max_length=5,
                verbose_name="Tryskání",
            ),
        ),
    ]
