# Generated by Django 5.2.1 on 2025-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_alter_bedna_rovnat_alter_bedna_tryskat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="tryskat",
            field=models.CharField(
                choices=[
                    ("--", "--------"),
                    ("CI", "Čistá"),
                    ("SP", "Špinavá"),
                    ("OT", "Otryskaná"),
                ],
                default="--",
                max_length=5,
                verbose_name="Tryskání",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="tryskat",
            field=models.CharField(
                choices=[
                    ("--", "--------"),
                    ("CI", "Čistá"),
                    ("SP", "Špinavá"),
                    ("OT", "Otryskaná"),
                ],
                default="--",
                max_length=5,
                verbose_name="Tryskání",
            ),
        ),
    ]
