# Generated by Django 5.2.1 on 2025-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0036_alter_bedna_tryskat_alter_historicalbedna_tryskat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="rovnat",
            field=models.CharField(
                choices=[
                    ("--", "--------"),
                    ("RO", "Rovná"),
                    ("KR", "Křivá"),
                    ("VY", "Vyrovnaná"),
                ],
                default="--",
                max_length=5,
                verbose_name="Rovnání",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="rovnat",
            field=models.CharField(
                choices=[
                    ("--", "--------"),
                    ("RO", "Rovná"),
                    ("KR", "Křivá"),
                    ("VY", "Vyrovnaná"),
                ],
                default="--",
                max_length=5,
                verbose_name="Rovnání",
            ),
        ),
    ]
