# Generated by Django 5.2.1 on 2025-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_alter_bedna_rovnat_alter_historicalbedna_rovnat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedna",
            name="dodatecne_info",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Sonder / Zusatzinfo",
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="dodatecne_info",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Sonder / Zusatzinfo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakazka",
            name="predpis",
            field=models.CharField(max_length=30, verbose_name="Předpis / Výkres"),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="predpis",
            field=models.CharField(max_length=30, verbose_name="Předpis / Výkres"),
        ),
    ]
