# Generated by Django 5.2.1 on 2025-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_bedna_dodatecne_info_historicalbedna_dodatecne_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedna",
            name="behalter_nr",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Behälter-Nr."
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="behalter_nr",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Behälter-Nr."
            ),
        ),
        migrations.AlterField(
            model_name="bedna",
            name="poznamka",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Poznámka HPM"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="poznamka",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Poznámka HPM"
            ),
        ),
    ]
