# Generated by Django 5.2.1 on 2025-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_remove_historicalzakaznik_cisla_beden_auto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="ciselna_rada",
            field=models.PositiveIntegerField(
                db_index=True,
                default=100000,
                help_text="Číselná řada pro automatické číslování beden - např. 100000, 200000, 300000 atd.",
                verbose_name="Číselná řada",
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="ciselna_rada",
            field=models.PositiveIntegerField(
                default=100000,
                help_text="Číselná řada pro automatické číslování beden - např. 100000, 200000, 300000 atd.",
                unique=True,
                verbose_name="Číselná řada",
            ),
        ),
    ]
