# Generated by Django 5.2.1 on 2025-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_alter_historicalzakaznik_ciselna_rada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="cislo_bedny",
            field=models.PositiveIntegerField(
                blank=True, unique=True, verbose_name="Číslo bedny"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="cislo_bedny",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, verbose_name="Číslo bedny"
            ),
        ),
        migrations.AlterField(
            model_name="historicalkamion",
            name="prijem_vydej",
            field=models.CharField(
                choices=[("P", "Přijem"), ("V", "Výdej")],
                default="P",
                max_length=1,
                verbose_name="Přijem/Výdej",
            ),
        ),
        migrations.AlterField(
            model_name="kamion",
            name="prijem_vydej",
            field=models.CharField(
                choices=[("P", "Přijem"), ("V", "Výdej")],
                default="P",
                max_length=1,
                verbose_name="Přijem/Výdej",
            ),
        ),
    ]
