# Generated by Django 5.2.1 on 2025-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0042_alter_bedna_cislo_bedny_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="sarze",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Šarže mat. / Charge"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="sarze",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Šarže mat. / Charge"
            ),
        ),
    ]
