# Generated by Django 5.2.1 on 2025-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_bedna_sarze_alter_historicalbedna_sarze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedna',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='historicalbedna',
            name='operator',
        ),
    ]
