# Generated by Django 5.2.1 on 2025-06-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_remove_bedna_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedna',
            old_name='zakazka_id',
            new_name='zakazka',
        ),
        migrations.RenameField(
            model_name='historicalbedna',
            old_name='zakazka_id',
            new_name='zakazka',
        ),
        migrations.RenameField(
            model_name='historicalkamion',
            old_name='zakaznik_id',
            new_name='zakaznik',
        ),
        migrations.RenameField(
            model_name='historicalzakazka',
            old_name='kamion_prijem_id',
            new_name='kamion_prijem',
        ),
        migrations.RenameField(
            model_name='historicalzakazka',
            old_name='kamion_vydej_id',
            new_name='kamion_vydej',
        ),
        migrations.RenameField(
            model_name='kamion',
            old_name='zakaznik_id',
            new_name='zakaznik',
        ),
        migrations.RenameField(
            model_name='zakazka',
            old_name='kamion_prijem_id',
            new_name='kamion_prijem',
        ),
        migrations.RenameField(
            model_name='zakazka',
            old_name='kamion_vydej_id',
            new_name='kamion_vydej',
        ),
    ]
