# Generated by Django 5.2.1 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_bedna_mnozstvi_historicalbedna_mnozstvi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzakazka',
            name='prubeh',
        ),
        migrations.RemoveField(
            model_name='zakazka',
            name='prubeh',
        ),
        migrations.AlterField(
            model_name='bedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Behälter-Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Behälter-Nr.'),
        ),
    ]
