# Generated by Django 5.2.1 on 2025-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_remove_historicalzakazka_prubeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='celozavitovy_vrut',
            field=models.BooleanField(default=False, verbose_name='Celozávit VG'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='celozavitovy_vrut',
            field=models.BooleanField(default=False, verbose_name='Celozávit VG'),
        ),
    ]
