# Generated by Django 5.2.1 on 2025-06-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_historicalzakazka_celozavitovy_vrut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalzakazka',
            old_name='celozavitovy_vrut',
            new_name='celozavit',
        ),
        migrations.RenameField(
            model_name='zakazka',
            old_name='celozavitovy_vrut',
            new_name='celozavit',
        ),
    ]
