# Generated by Django 5.2.1 on 2025-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_rename_celozavitovy_vrut_historicalzakazka_celozavit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzakazka',
            name='komplet',
        ),
        migrations.RemoveField(
            model_name='zakazka',
            name='komplet',
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='celozavit',
            field=models.BooleanField(default=False, verbose_name='Celozávit'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='celozavit',
            field=models.BooleanField(default=False, verbose_name='Celozávit'),
        ),
    ]
