# Generated by Django 5.2.1 on 2025-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_remove_historicalzakazka_komplet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='pouze_komplet',
            field=models.BooleanField(default=False, help_text='Zákazník může expedovat pouze kompletní zakázky, které mají všechny bedny ve stavu K_EXPEDICI.', verbose_name='Pouze kompletní zakázky'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='pouze_komplet',
            field=models.BooleanField(default=False, help_text='Zákazník může expedovat pouze kompletní zakázky, které mají všechny bedny ve stavu K_EXPEDICI.', verbose_name='Pouze kompletní zakázky'),
        ),
    ]
