# Generated by Django 5.2.1 on 2025-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0051_historicalzakaznik_pouze_komplet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedna",
            name="behalter_nr",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Č.bed. zák."
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="behalter_nr",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Č.bed. zák."
            ),
        ),
        migrations.AlterField(
            model_name="historicalzakaznik",
            name="vse_tryskat",
            field=models.BooleanField(
                default=False,
                help_text="Zákazník požaduje všechny bedny tryskat",
                verbose_name="Vše tryskat",
            ),
        ),
        migrations.AlterField(
            model_name="zakaznik",
            name="vse_tryskat",
            field=models.BooleanField(
                default=False,
                help_text="Zákazník požaduje všechny bedny tryskat",
                verbose_name="Vše tryskat",
            ),
        ),
    ]
