# Generated by Django 5.2.1 on 2025-06-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_bedna_behalter_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazka',
            name='kamion_prijem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zakazky_prijem', to='orders.kamion', verbose_name='Kamión příjem'),
        ),
    ]
