# Generated by Django 5.2.1 on 2025-06-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_alter_zakazka_kamion_prijem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='zkraceny_nazev',
            field=models.CharField(blank=True, db_index=True, help_text='Zkrácený název zákazníka,např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, null=True, verbose_name='Zkrácený název'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='zkraceny_nazev',
            field=models.CharField(blank=True, help_text='Zkrácený název zákazníka,např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, null=True, unique=True, verbose_name='Zkrácený název'),
        ),
    ]
