# Generated by Django 5.2.1 on 2025-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_historicalzakaznik_zkraceny_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='zkraceny_nazev',
            field=models.CharField(db_index=True, help_text='Zkrácený název zákazníka, např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, verbose_name='Zkrácený název'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='zkraceny_nazev',
            field=models.CharField(help_text='Zkrácený název zákazníka, např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, unique=True, verbose_name='Zkrácený název'),
        ),
    ]
