# Generated by Django 5.2.1 on 2025-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_historicalzakaznik_zkraceny_nazev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='prubeh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vorgang+'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='prubeh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vorgang+'),
        ),
    ]
