# Generated by Django 5.2.1 on 2025-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0057_alter_historicalzakazka_typ_hlavy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzakazka",
            name="typ_hlavy",
            field=models.CharField(
                choices=[("TK", "TK"), ("SK", "SK"), ("ZK", "ZK")],
                max_length=3,
                verbose_name="Typ hlavy",
            ),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="typ_hlavy",
            field=models.CharField(
                choices=[("TK", "TK"), ("SK", "SK"), ("ZK", "ZK")],
                max_length=3,
                verbose_name="Typ hlavy",
            ),
        ),
    ]
