# Generated by Django 5.2.1 on 2025-06-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_alter_historicalzakazka_typ_hlavy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='pouze_komplet',
            field=models.BooleanField(default=False, help_text='Zákazník může expedovat pouze kompletní zakázky, které mají všechny bedny ve stavu K_EXPEDICI.', verbose_name='Pouze komplet'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='pouze_komplet',
            field=models.BooleanField(default=False, help_text='Zákazník může expedovat pouze kompletní zakázky, které mají všechny bedny ve stavu K_EXPEDICI.', verbose_name='Pouze komplet'),
        ),
    ]
