# Generated by Django 5.2.1 on 2025-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0060_skupina_predpis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predpis",
            name="skupina",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Skupina TZ"
            ),
        ),
        migrations.DeleteModel(
            name="Skupina",
        ),
    ]
