# Generated by Django 5.2.1 on 2025-06-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0062_historicalpredpis"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpredpis",
            name="zakaznik",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.zakaznik",
                verbose_name="Zákazník",
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="zakaznik",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predpisy",
                to="orders.zakaznik",
                verbose_name="Zákazník",
            ),
            preserve_default=False,
        ),
    ]
