# Generated by Django 5.2.1 on 2025-06-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0063_historicalpredpis_zakaznik_predpis_zakaznik"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpredpis",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Předpis",
                "verbose_name_plural": "historical předpisy",
            },
        ),
        migrations.AlterModelOptions(
            name="predpis",
            options={
                "ordering": ["id"],
                "verbose_name": "Předpis",
                "verbose_name_plural": "předpisy",
            },
        ),
    ]
