# Generated by Django 5.2.1 on 2025-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_alter_historicalpredpis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpredpis',
            name='nazev',
            field=models.CharField(max_length=20, verbose_name='Název předpisu'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='nazev',
            field=models.CharField(max_length=20, verbose_name='Název předpisu'),
        ),
        migrations.AlterUniqueTogether(
            name='predpis',
            unique_together={('nazev', 'zakaznik')},
        ),
    ]
