# Generated by Django 5.2.1 on 2025-06-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_alter_historicalpredpis_nazev_alter_predpis_nazev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='predpis_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.predpis', verbose_name='Předpis / Výkres'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='predpis_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakazky', to='orders.predpis', verbose_name='Předpis / Výkres'),
        ),
    ]
