# Generated by Django 5.2.1 on 2025-06-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_historicalzakazka_predpis_fk_zakazka_predpis_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzakazka',
            name='predpis',
        ),
        migrations.RemoveField(
            model_name='zakazka',
            name='predpis',
        ),
    ]
