# Generated by Django 5.2.1 on 2025-06-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_remove_historicalzakazka_predpis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalzakazka',
            old_name='predpis_fk',
            new_name='predpis',
        ),
        migrations.RenameField(
            model_name='zakazka',
            old_name='predpis_fk',
            new_name='predpis',
        ),
    ]
