# Generated by Django 5.2.1 on 2025-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_rename_predpis_fk_historicalzakazka_predpis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Netto'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Netto'),
        ),
    ]
