# Generated by Django 5.2.1 on 2025-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_bedna_hmotnost_alter_historicalbedna_hmotnost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predpis',
            options={'ordering': ['zakaznik__zkratka', 'nazev'], 'verbose_name': 'Předpis', 'verbose_name_plural': 'předpisy'},
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='aktivni',
            field=models.BooleanField(default=True, help_text='Zda je předpis aktivní a může být přiřazen k zakázce.', verbose_name='Aktivní'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='jadro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jádro'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='krut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Krut'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='ohyb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ohyb'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='pletivo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pletivo'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='popousteni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Popouštění'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='povrch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Povrch'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='poznamka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='sarzovani',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šaržování'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='vrstva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vrstva'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='vyber_jadro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jádro - výběr'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='vyber_krut',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Krut - výběr'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='vyber_ohyb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ohyb - výběr'),
        ),
        migrations.AddField(
            model_name='historicalpredpis',
            name='vyber_povrch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Povrch - výběr'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='aktivni',
            field=models.BooleanField(default=True, help_text='Zda je předpis aktivní a může být přiřazen k zakázce.', verbose_name='Aktivní'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='jadro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jádro'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='krut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Krut'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='ohyb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ohyb'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='pletivo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pletivo'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='popousteni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Popouštění'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='povrch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Povrch'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='poznamka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='sarzovani',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šaržování'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='vrstva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vrstva'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='vyber_jadro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jádro - výběr'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='vyber_krut',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Krut - výběr'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='vyber_ohyb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ohyb - výběr'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='vyber_povrch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Povrch - výběr'),
        ),
    ]
