# Generated by Django 5.2.1 on 2025-06-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0070_alter_predpis_options_historicalpredpis_aktivni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpredpis",
            name="vyber_vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva - výběr"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="vyber_vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva - výběr"
            ),
        ),
    ]
