# Generated by Django 5.2.1 on 2025-06-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_historicalpredpis_vyber_vrstva_predpis_vyber_vrstva"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpredpis",
            old_name="vyber_jadro",
            new_name="popis_jadro",
        ),
        migrations.RenameField(
            model_name="historicalpredpis",
            old_name="vyber_krut",
            new_name="popis_krut",
        ),
        migrations.RenameField(
            model_name="historicalpredpis",
            old_name="vyber_ohyb",
            new_name="popis_ohyb",
        ),
        migrations.RenameField(
            model_name="historicalpredpis",
            old_name="vyber_povrch",
            new_name="popis_povrch",
        ),
        migrations.RenameField(
            model_name="historicalpredpis",
            old_name="vyber_vrstva",
            new_name="popis_vrstva",
        ),
        migrations.RenameField(
            model_name="predpis",
            old_name="vyber_jadro",
            new_name="popis_jadro",
        ),
        migrations.RenameField(
            model_name="predpis",
            old_name="vyber_krut",
            new_name="popis_krut",
        ),
        migrations.RenameField(
            model_name="predpis",
            old_name="vyber_ohyb",
            new_name="popis_ohyb",
        ),
        migrations.RenameField(
            model_name="predpis",
            old_name="vyber_povrch",
            new_name="popis_povrch",
        ),
        migrations.RenameField(
            model_name="predpis",
            old_name="vyber_vrstva",
            new_name="popis_vrstva",
        ),
    ]
