# Generated by Django 5.2.1 on 2025-06-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0072_rename_vyber_jadro_historicalpredpis_popis_jadro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_jadro",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Jádro - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_krut",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Krut - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_ohyb",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Ohyb - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_povrch",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Povrch - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_jadro",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Jádro - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_krut",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Krut - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_ohyb",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Ohyb - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_povrch",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Povrch - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vrstva - popis"
            ),
        ),
    ]
