# Generated by Django 5.2.1 on 2025-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0073_alter_historicalpredpis_popis_jadro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predpis",
            options={
                "ordering": ["-zakaznik__zkratka", "nazev"],
                "verbose_name": "Předpis",
                "verbose_name_plural": "předpisy",
            },
        ),
        migrations.AlterUniqueTogether(
            name="predpis",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="nazev",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Název předpisu"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="nazev",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Název předpisu"
            ),
        ),
    ]
