# Generated by Django 5.2.1 on 2025-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_alter_predpis_options_alter_predpis_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpredpis',
            name='popis_jadro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jádro - popis'),
        ),
        migrations.AlterField(
            model_name='historicalpredpis',
            name='popis_krut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Krut - popis'),
        ),
        migrations.AlterField(
            model_name='historicalpredpis',
            name='popis_ohyb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ohyb - popis'),
        ),
        migrations.AlterField(
            model_name='historicalpredpis',
            name='popis_povrch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Povrch - popis'),
        ),
        migrations.AlterField(
            model_name='historicalpredpis',
            name='popis_vrstva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vrstva - popis'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='popis_jadro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jádro - popis'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='popis_krut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Krut - popis'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='popis_ohyb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ohyb - popis'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='popis_povrch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Povrch - popis'),
        ),
        migrations.AlterField(
            model_name='predpis',
            name='popis_vrstva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vrstva - popis'),
        ),
    ]
