# Generated by Django 5.2.1 on 2025-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_alter_historicalpredpis_popis_jadro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfosfátovat'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfosfátovat'),
        ),
    ]
