# Generated by Django 5.2.1 on 2025-06-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_bedna_odfosfatovat_historicalbedna_odfosfatovat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfos.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfos.'),
        ),
    ]
