# Generated by Django 5.2.1 on 2025-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0080_alter_zakazka_predpis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpredpis",
            name="nazev",
            field=models.CharField(max_length=20, verbose_name="Název předpisu"),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="nazev",
            field=models.CharField(max_length=20, verbose_name="Název předpisu"),
        ),
    ]
