# Generated by Django 5.2.1 on 2025-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0082_alter_historicalpredpis_jadro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpredpis",
            name="jadro",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="krut",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="nazev",
            field=models.CharField(max_length=50, verbose_name="Název předpisu"),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="ohyb",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="pletivo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Pletivo"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popousteni",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Popouštění"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="povrch",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="sarzovani",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Šaržování"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="jadro",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="krut",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="nazev",
            field=models.CharField(max_length=50, verbose_name="Název předpisu"),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="ohyb",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="pletivo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Pletivo"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popousteni",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Popouštění"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="povrch",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="sarzovani",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Šaržování"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva"
            ),
        ),
    ]
