# Generated by Django 5.2.1 on 2025-06-25 08:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0083_alter_historicalpredpis_jadro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odberatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název odběratele')),
                ('zkraceny_nazev', models.CharField(help_text='Zkrácený název odběratele, např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, unique=True, verbose_name='Zkrácený název')),
                ('zkratka', models.CharField(max_length=3, unique=True, verbose_name='Zkratka')),
                ('adresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresa')),
                ('mesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Město')),
                ('stat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stát')),
                ('kontaktni_osoba', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontaktní osoba')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Odběratel',
                'verbose_name_plural': 'odběratelé',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOdberatel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nazev', models.CharField(db_index=True, max_length=100, verbose_name='Název odběratele')),
                ('zkraceny_nazev', models.CharField(db_index=True, help_text='Zkrácený název odběratele, např. pro zobrazení v kartě bedny a v přehledech.', max_length=15, verbose_name='Zkrácený název')),
                ('zkratka', models.CharField(db_index=True, max_length=3, verbose_name='Zkratka')),
                ('adresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresa')),
                ('mesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Město')),
                ('stat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stát')),
                ('kontaktni_osoba', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontaktní osoba')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Odběratel',
                'verbose_name_plural': 'historical odběratelé',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
