# Generated by Django 5.2.1 on 2025-06-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_odberatel_historicalodberatel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky'},
        ),
        migrations.RemoveField(
            model_name='historicalzakazka',
            name='zinkovna',
        ),
        migrations.RemoveField(
            model_name='zakazka',
            name='zinkovna',
        ),
        migrations.AddField(
            model_name='historicalkamion',
            name='odberatel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.odberatel', verbose_name='Odběratel'),
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='odberatel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.odberatel', verbose_name='Odběratel'),
        ),
        migrations.AddField(
            model_name='kamion',
            name='odberatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kamiony', to='orders.odberatel', verbose_name='Odběratel'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='odberatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zakazky', to='orders.odberatel', verbose_name='Odběratel'),
        ),
    ]
