# Generated by Django 5.2.1 on 2025-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_alter_zakazka_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkamion',
            name='misto_expedice',
        ),
        migrations.RemoveField(
            model_name='kamion',
            name='misto_expedice',
        ),
        migrations.AddField(
            model_name='historicalodberatel',
            name='psc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSČ'),
        ),
        migrations.AddField(
            model_name='historicalzakaznik',
            name='psc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSČ'),
        ),
        migrations.AddField(
            model_name='odberatel',
            name='psc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSČ'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='psc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSČ'),
        ),
    ]
