# Generated by Django 5.2.1 on 2025-06-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_remove_historicalkamion_misto_expedice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkamion',
            old_name='cislo_dl',
            new_name='cislo_dl_zakaznika',
        ),
        migrations.RenameField(
            model_name='kamion',
            old_name='cislo_dl',
            new_name='cislo_dl_zakaznika',
        ),
    ]
