# Generated by Django 5.2.1 on 2025-06-25 12:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_historicalkamion_poradove_cislo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prumer', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Průměr')),
                ('delka', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Délka')),
                ('hlava', models.CharField(choices=[('TK', 'TK'), ('SK', 'SK'), ('ZK', 'ZK')], max_length=3, verbose_name='Typ hlavy')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (Kč/kg)')),
                ('predpis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceny', to='orders.predpis', verbose_name='Předpis')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceny', to='orders.zakaznik', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'ceny',
                'ordering': ['zakaznik__nazev', 'predpis__nazev', 'prumer', 'delka', 'hlava'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCena',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('prumer', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Průměr')),
                ('delka', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Délka')),
                ('hlava', models.CharField(choices=[('TK', 'TK'), ('SK', 'SK'), ('ZK', 'ZK')], max_length=3, verbose_name='Typ hlavy')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (Kč/kg)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('predpis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.predpis', verbose_name='Předpis')),
                ('zakaznik', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.zakaznik', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'historical Cena',
                'verbose_name_plural': 'historical ceny',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
