# Generated by Django 5.2.1 on 2025-06-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0090_typhlavy_historicaltyphlavy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzakazka',
            name='typ_hlavy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.typhlavy', verbose_name='Typ hlavy'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='typ_hlavy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakazky', to='orders.typhlavy', verbose_name='Typ hlavy'),
        ),
    ]
