# Generated by Django 5.2.1 on 2025-06-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0091_alter_historicalzakazka_typ_hlavy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cena',
            options={'ordering': ['zakaznik__nazev', 'predpis__nazev', 'prumer', 'delka'], 'verbose_name': 'Cena', 'verbose_name_plural': 'ceny'},
        ),
        migrations.RemoveField(
            model_name='cena',
            name='hlava',
        ),
        migrations.RemoveField(
            model_name='historicalcena',
            name='hlava',
        ),
    ]
