# Generated by Django 5.2.1 on 2025-06-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0092_alter_cena_options_remove_cena_hlava_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazka',
            name='typ_hlavy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zakazky', to='orders.typhlavy', verbose_name='Typ hlavy'),
        ),
    ]
