# Generated by Django 5.2.1 on 2025-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0093_alter_zakazka_typ_hlavy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cena',
            options={'ordering': ['zakaznik__nazev', 'predpis__nazev', 'prumer', 'delka_min'], 'verbose_name': 'Cena', 'verbose_name_plural': 'ceny'},
        ),
        migrations.RemoveField(
            model_name='cena',
            name='delka',
        ),
        migrations.RemoveField(
            model_name='historicalcena',
            name='delka',
        ),
        migrations.AddField(
            model_name='cena',
            name='delka_max',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Délka do (vyjma)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cena',
            name='delka_min',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Délka od (včetně)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='delka_max',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Délka do (vyjma)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='delka_min',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Délka od (včetně)'),
            preserve_default=False,
        ),
    ]
