# Generated by Django 5.2.1 on 2025-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0094_alter_cena_options_remove_cena_delka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcena',
            name='predpis',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='predpis',
        ),
        migrations.AddField(
            model_name='cena',
            name='predpis',
            field=models.ManyToManyField(help_text='Předpisy, ke kterým se cena vztahuje. Může být více předpisů pro daný průměr a cenu.', related_name='ceny', to='orders.predpis', verbose_name='Předpisy'),
        ),
    ]
