# Generated by Django 5.2.1 on 2025-06-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0095_remove_historicalcena_predpis_remove_cena_predpis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cena',
            options={'ordering': ['zakaznik__nazev', 'predpis__nazev', 'delka_min'], 'verbose_name': 'Cena', 'verbose_name_plural': 'ceny'},
        ),
        migrations.RemoveField(
            model_name='cena',
            name='prumer',
        ),
        migrations.RemoveField(
            model_name='historicalcena',
            name='prumer',
        ),
    ]
