# Generated by Django 5.2.1 on 2025-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0096_alter_cena_options_remove_cena_prumer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cena',
            options={'ordering': ['zakaznik__nazev', 'delka_min'], 'verbose_name': 'Cena', 'verbose_name_plural': 'ceny'},
        ),
        migrations.AddField(
            model_name='cena',
            name='popis',
            field=models.CharField(default=1, max_length=50, verbose_name='Popis ceny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='popis',
            field=models.CharField(default=1, max_length=50, verbose_name='Popis ceny'),
            preserve_default=False,
        ),
    ]
