# Generated by Django 5.2.1 on 2025-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0097_alter_cena_options_cena_popis_historicalcena_popis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cena',
            options={'ordering': ['popis', 'delka_min'], 'verbose_name': 'Cena', 'verbose_name_plural': 'ceny'},
        ),
    ]
