# Generated by Django 5.2.1 on 2025-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0098_alter_cena_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cena',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='historicalcena',
            name='cena',
        ),
        migrations.AddField(
            model_name='cena',
            name='cena_za_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cena (EUR/kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='cena_za_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cena (EUR/kg)'),
            preserve_default=False,
        ),
    ]
