# Generated by Django 5.2.1 on 2025-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0099_remove_cena_cena_remove_historicalcena_cena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='predpis',
            field=models.ManyToManyField(blank=True, help_text='Předpisy, ke kterým se cena vztahuje. Může být více předpisů pro daný průměr a cenu.', null=True, related_name='ceny', to='orders.predpis', verbose_name='Předpisy'),
        ),
    ]
