# Generated by Django 5.2.1 on 2025-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0100_alter_cena_predpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='predpis',
            field=models.ManyToManyField(blank=True, help_text='Předpisy, ke kterým se cena vztahuje. Může být více předpisů pro daný průměr a cenu.', related_name='ceny', to='orders.predpis', verbose_name='Předpisy'),
        ),
    ]
