# Generated by Django 5.2.1 on 2025-07-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0101_alter_cena_predpis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkamion',
            old_name='cislo_dl_zakaznika',
            new_name='cislo_dl',
        ),
        migrations.RenameField(
            model_name='kamion',
            old_name='cislo_dl_zakaznika',
            new_name='cislo_dl',
        ),
    ]
