# Generated by Django 5.2.1 on 2025-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0102_rename_cislo_dl_zakaznika_historicalkamion_cislo_dl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kamion',
            options={'ordering': ['-id'], 'verbose_name': 'Kamión', 'verbose_name_plural': 'kamióny'},
        ),
        migrations.AddField(
            model_name='historicalzakaznik',
            name='zkratka_statu',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Zkratka státu'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='zkratka_statu',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Zkratka státu'),
        ),
    ]
