# Generated by Django 5.2.1 on 2025-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0103_alter_kamion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalodberatel',
            name='zkratka_statu',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Zkratka státu'),
        ),
        migrations.AddField(
            model_name='odberatel',
            name='zkratka_statu',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Zkratka státu'),
        ),
    ]
