# Generated by Django 5.2.1 on 2025-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0104_historicalodberatel_zkratka_statu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Bedna je pozastavena a nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Bedna je pozastavena a nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno'),
        ),
        migrations.AlterField(
            model_name='historicalzakazka',
            name='priorita',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', '-')], default='P3', max_length=5, verbose_name='Priorita'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='priorita',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', '-')], default='P3', max_length=5, verbose_name='Priorita'),
        ),
    ]
