# Generated by Django 5.2.1 on 2025-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0105_bedna_pozastaveno_historicalbedna_pozastaveno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Pokud je bedna pozastavena, nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Pokud je bedna pozastavena, nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno'),
        ),
    ]
