# Generated by Django 5.2.1 on 2025-07-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0106_alter_bedna_pozastaveno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('can_change_expedovana_bedna', 'Může upravovat expedované bedny'),), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'permissions': (('can_change_expedovana_zakazka', 'Může upravovat expedované zakázky'),), 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky'},
        ),
    ]
