# Generated by Django 5.2.1 on 2025-07-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0107_alter_bedna_options_alter_zakazka_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('can_change_expedovana_bedna', 'Může upravovat expedované bedny'), ('can_change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
    ]
