# Generated by Django 5.2.1 on 2025-07-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0108_alter_bedna_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_bedna', 'Může upravovat expedované bedny'), ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_zakazka', 'Může upravovat expedované zakázky'),), 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky'},
        ),
    ]
