# Generated by Django 5.2.1 on 2025-08-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0109_alter_bedna_options_alter_zakazka_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, unique=True, verbose_name='Kód pozice')),
                ('kapacita', models.PositiveIntegerField(default=15, verbose_name='Kapacita')),
            ],
            options={
                'verbose_name': 'Pozice',
                'verbose_name_plural': 'pozice',
                'ordering': ['kod'],
            },
        ),
        migrations.AlterField(
            model_name='bedna',
            name='rovnat',
            field=models.CharField(choices=[('--', '--------'), ('RO', 'Rovná'), ('KR', 'Křivá'), ('RS', 'Rovná se'), ('VY', 'Vyrovnaná')], default='--', max_length=5, verbose_name='Rovnání'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='rovnat',
            field=models.CharField(choices=[('--', '--------'), ('RO', 'Rovná'), ('KR', 'Křivá'), ('RS', 'Rovná se'), ('VY', 'Vyrovnaná')], default='--', max_length=5, verbose_name='Rovnání'),
        ),
        migrations.AddField(
            model_name='bedna',
            name='pozice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bedny', to='orders.pozice', verbose_name='Pozice'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='pozice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.pozice', verbose_name='Pozice'),
        ),
    ]
