# Generated by Django 5.2.1 on 2025-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0110_pozice_alter_bedna_rovnat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozice',
            name='kod',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1, unique=True, verbose_name='Kód pozice'),
        ),
    ]
