# Generated by Django 5.2.1 on 2025-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0111_alter_pozice_kod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzakazka",
            name="priorita",
            field=models.CharField(
                choices=[("P1", "P1"), ("P2", "P2"), ("P3", "--")],
                default="P3",
                max_length=5,
                verbose_name="Priorita",
            ),
        ),
        migrations.AlterField(
            model_name="pozice",
            name="kod",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=1,
                unique=True,
                verbose_name="Kód pozice",
            ),
        ),
        migrations.AlterField(
            model_name="zakazka",
            name="priorita",
            field=models.CharField(
                choices=[("P1", "P1"), ("P2", "P2"), ("P3", "--")],
                default="P3",
                max_length=5,
                verbose_name="Priorita",
            ),
        ),
    ]
