# Generated by Django 5.2.1 on 2025-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0112_alter_historicalzakazka_priorita_alter_pozice_kod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='poznamka_k_navezeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poznámka k navezení'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='poznamka_k_navezeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poznámka k navezení'),
        ),
    ]
