# Generated by Django 5.2.1 on 2025-09-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0113_bedna_poznamka_k_navezeni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Číslo bedny zákazníka'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Netto kg'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='mnozstvi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Množství ks'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfos.?'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Pokud je bedna pozastavena, nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno?'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže materiálu / Charge'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Tára kg'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Číslo bedny zákazníka'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='hmotnost',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Netto kg'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='mnozstvi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Množství ks'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='odfosfatovat',
            field=models.BooleanField(default=False, verbose_name='Odfos.?'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='pozastaveno',
            field=models.BooleanField(default=False, help_text='Pokud je bedna pozastavena, nelze s ní pracovat, dokud ji odpovědná osoba neuvolní.', verbose_name='Pozastaveno?'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže materiálu / Charge'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Tára kg'),
        ),
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='zkratka',
            field=models.CharField(db_index=True, help_text='Zkratka zákazníka, např. pro automatické číslování beden a kamionů a pro programové použití. Zkratka po vytvoření nemůže být změněna.', max_length=3, verbose_name='Zkratka'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='kamion_vydej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakazky_vydej', to='orders.kamion', verbose_name='Kamión výdej'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='zkratka',
            field=models.CharField(help_text='Zkratka zákazníka, např. pro automatické číslování beden a kamionů a pro programové použití. Zkratka po vytvoření nemůže být změněna.', max_length=3, unique=True, verbose_name='Zkratka'),
        ),
    ]
