# Generated by Django 5.2.1 on 2025-09-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0114_alter_bedna_behalter_nr_alter_bedna_hmotnost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamion',
            name='zakaznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kamiony', to='orders.zakaznik', verbose_name='Zákazník'),
        ),
    ]
