# Generated by Django 5.2.1 on 2025-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0115_alter_kamion_zakaznik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodberatel',
            name='zkraceny_nazev',
            field=models.CharField(db_index=True, help_text='Zkrácený název odběratele.', max_length=15, verbose_name='Zkrácený název'),
        ),
        migrations.AlterField(
            model_name='historicalodberatel',
            name='zkratka',
            field=models.CharField(db_index=True, help_text='Zkratka odběratele, např. pro programové použití. Zkratka po vytvoření nemůže být změněna.', max_length=3, verbose_name='Zkratka'),
        ),
        migrations.AlterField(
            model_name='odberatel',
            name='zkraceny_nazev',
            field=models.CharField(help_text='Zkrácený název odběratele.', max_length=15, unique=True, verbose_name='Zkrácený název'),
        ),
        migrations.AlterField(
            model_name='odberatel',
            name='zkratka',
            field=models.CharField(help_text='Zkratka odběratele, např. pro programové použití. Zkratka po vytvoření nemůže být změněna.', max_length=3, unique=True, verbose_name='Zkratka'),
        ),
    ]
