# Generated by Django 5.2.1 on 2025-09-23 19:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0116_alter_historicalodberatel_zkraceny_nazev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedna",
            name="brutto",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Brutto kg",
            ),
        ),
        migrations.AddField(
            model_name="historicalbedna",
            name="brutto",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Brutto kg",
            ),
        ),
        migrations.AlterField(
            model_name="bedna",
            name="hmotnost",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Netto kg",
            ),
        ),
        migrations.AlterField(
            model_name="bedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Tára kg",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="hmotnost",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Netto kg",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbedna",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"), message="Hmotnost musí být kladné číslo."
                    )
                ],
                verbose_name="Tára kg",
            ),
        ),
    ]
