# Generated by Django 5.2.1 on 2025-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0119_alter_bedna_hmotnost_alter_bedna_tara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('NE', 'Nepřijato'), ('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='NE', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='stav_bedny',
            field=models.CharField(choices=[('NE', 'Nepřijato'), ('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Do zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='NE', max_length=2, verbose_name='Stav bedny'),
        ),
    ]
