# Generated by Django 5.2.1 on 2025-09-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0120_alter_bedna_stav_bedny_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedna",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("change_expedovana_bedna", "Může upravovat expedované bedny"),
                    (
                        "change_pozastavena_bedna",
                        "Může upravovat a uvolnit pozastavené bedny",
                    ),
                    (
                        "change_neprijata_bedna",
                        "Může upravovat bedny ve stavu NEPŘIJATO",
                    ),
                ),
                "verbose_name": "Bedna",
                "verbose_name_plural": "bedny",
            },
        ),
    ]
