# Generated by Django 5.2.1 on 2025-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0121_alter_bedna_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bedna',
            constraint=models.CheckConstraint(condition=models.Q(('stav_bedny', 'NE'), models.Q(('hmotnost__isnull', False), ('mnozstvi__isnull', False), ('tara__isnull', False), ('hmotnost__gt', 0), ('mnozstvi__gt', 0), ('tara__gt', 0)), _connector='OR'), name='bedna_valid_when_not_neprijato'),
        ),
    ]
