# Generated by Django 5.2.1 on 2025-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0122_bedna_bedna_valid_when_not_neprijato"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpredpis",
            name="popis_jadro_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro - popis"
            ),
        ),
        migrations.AddField(
            model_name="historicalpredpis",
            name="popis_krut_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut - popis"
            ),
        ),
        migrations.AddField(
            model_name="historicalpredpis",
            name="popis_ohyb_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb - popis"
            ),
        ),
        migrations.AddField(
            model_name="historicalpredpis",
            name="popis_povrch_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch - popis"
            ),
        ),
        migrations.AddField(
            model_name="historicalpredpis",
            name="popis_vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 2 - popis"
            ),
        ),
        migrations.AddField(
            model_name="historicalpredpis",
            name="vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 2"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="popis_jadro_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro - popis"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="popis_krut_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut - popis"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="popis_ohyb_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb - popis"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="popis_povrch_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch - popis"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="popis_vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 2 - popis"
            ),
        ),
        migrations.AddField(
            model_name="predpis",
            name="vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 2"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 1 - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 1"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 1 - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva 1"
            ),
        ),
    ]
