# Generated by Django 5.2.1 on 2025-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0123_historicalpredpis_popis_jadro_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_jadro_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_krut_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_ohyb_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva - popis"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpredpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_jadro_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jádro - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_krut_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Krut - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_ohyb_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ohyb - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva - popis"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_vrstva_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="vrstva",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vrstva"
            ),
        ),
    ]
