# Generated by Django 5.2.1 on 2025-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0124_alter_historicalpredpis_popis_jadro_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpredpis",
            name="popis_povrch_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch - popis 2"
            ),
        ),
        migrations.AlterField(
            model_name="predpis",
            name="popis_povrch_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Povrch - popis 2"
            ),
        ),
    ]
