# Generated by Django 5.2.1 on 2025-10-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0126_pletivo_historicalpletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpredpis',
            name='pletivo_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.pletivo', verbose_name='Pletivo'),
        ),
        migrations.AddField(
            model_name='predpis',
            name='pletivo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predpisy', to='orders.pletivo', verbose_name='Pletivo'),
        ),
    ]
