# Generated by Django 5.2.1 on 2025-10-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0127_historicalpredpis_pletivo_fk_predpis_pletivo_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpredpis',
            name='pletivo',
        ),
        migrations.RemoveField(
            model_name='predpis',
            name='pletivo',
        ),
    ]
