# Generated by Django 5.2.1 on 2025-10-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0128_remove_historicalpredpis_pletivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpredpis',
            old_name='pletivo_fk',
            new_name='pletivo',
        ),
        migrations.RenameField(
            model_name='predpis',
            old_name='pletivo_fk',
            new_name='pletivo',
        ),
    ]
