# Generated by Django 5.2.1 on 2025-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0129_rename_pletivo_fk_historicalpredpis_pletivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FA / Bestell Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FA / Bestell Nr.'),
        ),
    ]
