# Generated by Django 5.2.1 on 2025-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0130_alter_bedna_vyrobni_zakazka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže mat. / Charge'),
        ),
        migrations.AlterField(
            model_name='bedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FA / Bestell-Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='sarze',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šarže mat. / Charge'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='vyrobni_zakazka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FA / Bestell-Nr.'),
        ),
    ]
