# Generated by Django 5.2.1 on 2025-10-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0131_alter_bedna_sarze_alter_bedna_vyrobni_zakazka_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoziceZakazkaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poradi",
                    models.IntegerField(default=0, verbose_name="Pořadí v pozici"),
                ),
                (
                    "pozice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zakazky_poradi",
                        to="orders.pozice",
                    ),
                ),
                (
                    "zakazka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozice_poradi",
                        to="orders.zakazka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pořadí zakázky v pozici",
                "verbose_name_plural": "Pořadí zakázek v pozici",
            },
        ),
    ]
