# Generated by Django 5.2.1 on 2025-10-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0132_pozicezakazkaorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pozicezakazkaorder",
            options={
                "ordering": ["pozice__kod", "poradi", "zakazka_id"],
                "verbose_name": "Pořadí zakázky v pozici",
                "verbose_name_plural": "Pořadí zakázek v pozici",
            },
        ),
        migrations.AlterField(
            model_name="pozicezakazkaorder",
            name="poradi",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Pořadí v pozici"
            ),
        ),
        migrations.AddConstraint(
            model_name="pozicezakazkaorder",
            constraint=models.UniqueConstraint(
                fields=("pozice", "zakazka"), name="uniq_pozice_zakazka"
            ),
        ),
        migrations.AddConstraint(
            model_name="pozicezakazkaorder",
            constraint=models.UniqueConstraint(
                fields=("pozice", "poradi"), name="uniq_pozice_poradi"
            ),
        ),
    ]
