# Generated by Django 5.2.1 on 2025-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0133_alter_pozicezakazkaorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_bedna', 'Může upravovat expedované bedny'), ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny'), ('change_neprijata_bedna', 'Může upravovat bedny ve stavu NEPŘIJATO'), ('mark_bedna_navezeno', 'Může označit bednu jako navezenou')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
    ]
