# Generated by Django 5.2.8 on 2025-11-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0134_alter_bedna_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakazkaMereni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvrdost_povrchu', models.CharField(max_length=50, verbose_name='tvrdost_povrchu')),
                ('tvrdost_jadra', models.CharField(max_length=50, verbose_name='tvrdost_jadra')),
                ('ohyb', models.CharField(max_length=50, verbose_name='ohyb')),
                ('krut', models.CharField(max_length=50, verbose_name='krut')),
                ('hazeni', models.CharField(max_length=50, verbose_name='hazeni')),
                ('kamion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazky_mereni', to='orders.kamion', verbose_name='Kamión')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mereni', to='orders.zakazka', verbose_name='Zakázka')),
            ],
            options={
                'verbose_name': 'Měření zakázky',
                'verbose_name_plural': 'Měření zakázek',
                'ordering': ['zakazka', 'id'],
            },
        ),
    ]
