# Generated by Django 5.2.8 on 2025-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0135_zakazkamereni'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='hazeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Házení'),
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='krut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Krut'),
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='ohyb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ohyb'),
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='tvrdost_jadra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tvrdost jádra'),
        ),
        migrations.AddField(
            model_name='historicalzakazka',
            name='tvrdost_povrchu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tvrdost povrchu'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='hazeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Házení'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='krut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Krut'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='ohyb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ohyb'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='tvrdost_jadra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tvrdost jádra'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='tvrdost_povrchu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tvrdost povrchu'),
        ),
        migrations.DeleteModel(
            name='ZakazkaMereni',
        ),
    ]
