# Generated by Django 5.2.8 on 2025-11-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0136_historicalzakazka_hazeni_historicalzakazka_krut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakazka',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_zakazka', 'Může upravovat expedované zakázky'), ('change_mereni_zakazky', 'Může upravovat měření v zakázce')), 'verbose_name': 'Zakázka', 'verbose_name_plural': 'zakázky'},
        ),
    ]
