# Generated by Django 5.2.8 on 2025-11-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0137_alter_zakazka_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_bedna', 'Může upravovat expedované bedny'), ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny'), ('change_neprijata_bedna', 'Může upravovat bedny ve stavu NEPŘIJATO'), ('mark_bedna_navezeno', 'Může označit bednu jako navezenou a vrátit ji zpět na příjem')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
    ]
