# Generated by Django 5.2.8 on 2025-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0138_alter_bedna_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rozpracovanost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_zaznamu', models.DateTimeField(auto_now_add=True, verbose_name='Čas záznamu')),
                ('zakaznik', models.CharField(max_length=50, verbose_name='Zákazník')),
                ('beden_rozpracovanych', models.PositiveIntegerField(verbose_name='Počet rozpracovaných beden')),
                ('cena_za_kaleni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za kalení €')),
            ],
            options={
                'verbose_name': 'Rozpracovanost',
                'verbose_name_plural': 'rozpracovanosti',
                'ordering': ['-cas_zaznamu'],
            },
        ),
    ]
