# Generated by Django 5.2.8 on 2025-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0139_rozpracovanost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozpracovanost',
            name='beden_rozpracovanych',
        ),
        migrations.RemoveField(
            model_name='rozpracovanost',
            name='cena_za_kaleni',
        ),
        migrations.RemoveField(
            model_name='rozpracovanost',
            name='zakaznik',
        ),
        migrations.AddField(
            model_name='rozpracovanost',
            name='bedny',
            field=models.ManyToManyField(related_name='rozpracovanost_zaznamy', to='orders.bedna', verbose_name='Bedny'),
        ),
    ]
