# Generated by Django 5.2.8 on 2025-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0140_remove_rozpracovanost_beden_rozpracovanych_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkamion',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka pro DL'),
        ),
        migrations.AddField(
            model_name='kamion',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka pro DL'),
        ),
    ]
