# Generated by Django 5.2.8 on 2025-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0141_historicalkamion_poznamka_kamion_poznamka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkamion',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka do DL'),
        ),
        migrations.AlterField(
            model_name='kamion',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka do DL'),
        ),
    ]
