# Generated by Django 5.2.8 on 2025-12-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0142_alter_historicalkamion_poznamka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='cena_rovnani_za_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena rovnání (EUR/kg)'),
        ),
        migrations.AddField(
            model_name='cena',
            name='cena_tryskani_za_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena tryskání (EUR/kg)'),
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='cena_rovnani_za_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena rovnání (EUR/kg)'),
        ),
        migrations.AddField(
            model_name='historicalcena',
            name='cena_tryskani_za_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena tryskání (EUR/kg)'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='cena_za_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena kalení (EUR/kg)'),
        ),
        migrations.AlterField(
            model_name='historicalcena',
            name='cena_za_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena kalení (EUR/kg)'),
        ),
    ]
