# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0143_cena_cena_rovnani_za_kg_cena_cena_tryskani_za_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='fakturovat',
            field=models.BooleanField(default=True, help_text='Pokud není bedna určena k fakturaci, nebude zahrnuta do proforma faktury pro zákazníka.', verbose_name='Fakturovat?'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='fakturovat',
            field=models.BooleanField(default=True, help_text='Pokud není bedna určena k fakturaci, nebude zahrnuta do proforma faktury pro zákazníka.', verbose_name='Fakturovat?'),
        ),
    ]
