# Generated by Django 5.2.8 on 2025-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0144_bedna_fakturovat_historicalbedna_fakturovat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkamion',
            name='text_upozorneni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text upozornění na DL'),
        ),
        migrations.AddField(
            model_name='kamion',
            name='text_upozorneni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text upozornění na DL'),
        ),
    ]
