# Generated by Django 5.2.8 on 2026-01-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0145_historicalkamion_text_upozorneni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='mnozstvi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Množ. ks'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='mnozstvi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Množ. ks'),
        ),
    ]
