# Generated by Django 5.2.8 on 2026-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0146_alter_bedna_mnozstvi_alter_historicalbedna_mnozstvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='fakturovat_rovnani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat rovnání pokud byla bedna vyrovnána.', verbose_name='Fakt. rovnání'),
        ),
        migrations.AddField(
            model_name='historicalzakaznik',
            name='fakturovat_tryskani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat tryskání pokud byla bedna otryskána.', verbose_name='Fakt. tryskání'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='fakturovat_rovnani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat rovnání pokud byla bedna vyrovnána.', verbose_name='Fakt. rovnání'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='fakturovat_tryskani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat tryskání pokud byla bedna otryskána.', verbose_name='Fakt. tryskání'),
        ),
    ]
