# Generated by Django 5.2.8 on 2026-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0147_historicalzakaznik_fakturovat_rovnani_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='fakturovat_rovnani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat rovnání pokud byla bedna vyrovnána.', verbose_name='Fakturovat rovnání'),
        ),
        migrations.AlterField(
            model_name='historicalzakaznik',
            name='fakturovat_tryskani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat tryskání pokud byla bedna otryskána.', verbose_name='Fakturovat tryskání'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='fakturovat_rovnani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat rovnání pokud byla bedna vyrovnána.', verbose_name='Fakturovat rovnání'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='fakturovat_tryskani',
            field=models.BooleanField(default=False, help_text='Zákazníkovi se bude fakturovat tryskání pokud byla bedna otryskána.', verbose_name='Fakturovat tryskání'),
        ),
    ]
