# Generated by Django 5.2.8 on 2026-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0148_alter_historicalzakaznik_fakturovat_rovnani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='proforma_po_bednach',
            field=models.BooleanField(default=False, help_text='Zákazník požaduje vystavení faktury po jednotlivých bednách.', verbose_name='Proforma po bednách'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='proforma_po_bednach',
            field=models.BooleanField(default=False, help_text='Zákazník požaduje vystavení faktury po jednotlivých bednách.', verbose_name='Proforma po bednách'),
        ),
    ]
