# Generated by Django 5.2.8 on 2026-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0149_historicalzakaznik_proforma_po_bednach_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkamion",
            name="prepsani_hmotnosti_brutto",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Pokud je vyplněno, použije se tato hmotnost brutto na dodacím listu místo vypočtené hodnoty.",
                max_digits=8,
                null=True,
                verbose_name="Přepsání hmotnosti brutto",
            ),
        ),
        migrations.AddField(
            model_name="kamion",
            name="prepsani_hmotnosti_brutto",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Pokud je vyplněno, použije se tato hmotnost brutto na dodacím listu místo vypočtené hodnoty.",
                max_digits=8,
                null=True,
                verbose_name="Přepsání hmotnosti brutto",
            ),
        ),
    ]
