# Generated by Django 5.2.8 on 2026-01-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0150_historicalkamion_prepsani_hmotnosti_brutto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='puvodni_zakazka',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Odkaz na původní zakázku, ze které byla tato oddělena při expedici.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.zakazka', verbose_name='Původní zakázka'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='puvodni_zakazka',
            field=models.ForeignKey(blank=True, help_text='Odkaz na původní zakázku, ze které byla tato oddělena při expedici.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oddelene_zakazky', to='orders.zakazka', verbose_name='Původní zakázka'),
        ),
        migrations.AlterField(
            model_name='historicalkamion',
            name='text_upozorneni',
            field=models.CharField(blank=True, help_text='Text upozornění pro bedny, které se nefakturují. Je stejně podbarven jako tyto bedny v dodacím listu.', max_length=100, null=True, verbose_name='Text upozornění na DL'),
        ),
        migrations.AlterField(
            model_name='kamion',
            name='text_upozorneni',
            field=models.CharField(blank=True, help_text='Text upozornění pro bedny, které se nefakturují. Je stejně podbarven jako tyto bedny v dodacím listu.', max_length=100, null=True, verbose_name='Text upozornění na DL'),
        ),
    ]
