# Generated by Django 5.2.8 on 2026-01-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0151_historicalzakazka_puvodni_zakazka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_bedna', 'Může upravovat expedované bedny'), ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny'), ('change_neprijata_bedna', 'Může upravovat bedny ve stavu NEPŘIJATO'), ('change_poznamka_neprijata_bedna', 'Může upravovat poznámku u bedny ve stavu NEPŘIJATO'), ('mark_bedna_navezeno', 'Může označit bednu jako navezenou a vrátit ji zpět na příjem')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
    ]
