# Generated by Django 5.2.8 on 2026-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0152_alter_bedna_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakazka',
            name='udaje_zadal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Údaje zadal'),
        ),
        migrations.AddField(
            model_name='zakazka',
            name='udaje_zadal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Údaje zadal'),
        ),
    ]
