# Generated by Django 5.2.8 on 2026-01-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0153_historicalzakazka_udaje_zadal_zakazka_udaje_zadal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzakazka',
            name='udaje_zadal',
        ),
        migrations.RemoveField(
            model_name='zakazka',
            name='udaje_zadal',
        ),
    ]
