# Generated by Django 5.2.8 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0154_remove_historicalzakazka_udaje_zadal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Č. b. zák.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='behalter_nr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Č. b. zák.'),
        ),
    ]
