# Generated by Django 5.2.8 on 2026-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0155_alter_bedna_behalter_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='behalter_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Č. b. zák.'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='behalter_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Č. b. zák.'),
        ),
    ]
