# Generated by Django 5.2.8 on 2026-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0156_alter_bedna_behalter_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'K zinkování'), ('NZ', 'Na zinkování'), ('PZ', 'Po zinkování'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
        migrations.AddField(
            model_name='historicalbedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'K zinkování'), ('NZ', 'Na zinkování'), ('PZ', 'Po zinkování'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
    ]
