# Generated by Django 5.2.8 on 2026-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0157_bedna_zinkovat_historicalbedna_zinkovat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'K zinkování'), ('NZ', 'Na zinkování'), ('PZ', 'Pozinkováno'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'K zinkování'), ('NZ', 'Na zinkování'), ('PZ', 'Pozinkováno'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
    ]
