# Generated by Django 5.2.8 on 2026-02-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0158_alter_bedna_zinkovat_alter_historicalbedna_zinkovat"),
    ]

    def forwards_copy_snapshot(apps, schema_editor):
        Rozpracovanost = apps.get_model("orders", "Rozpracovanost")
        Bedna = apps.get_model("orders", "Bedna")
        Snapshot = apps.get_model("orders", "RozpracovanostBednaSnapshot")

        # Starý through model pro původní M2M (bez through=)
        OldThrough = Rozpracovanost.bedny.through

        snapshots = []
        for link in OldThrough.objects.select_related("bedna"):
            bedna = link.bedna
            if bedna is None:
                continue
            snapshots.append(
                Snapshot(
                    rozpracovanost_id=link.rozpracovanost_id,
                    bedna_id=bedna.pk,
                    stav_bedny=bedna.stav_bedny,
                    tryskat=bedna.tryskat,
                    rovnat=bedna.rovnat,
                    zinkovat=bedna.zinkovat,
                )
            )

        if snapshots:
            Snapshot.objects.bulk_create(snapshots, batch_size=500)

    operations = [
        migrations.CreateModel(
            name="RozpracovanostBednaSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stav_bedny",
                    models.CharField(
                        choices=[
                            ("NE", "Nepřijato"),
                            ("PR", "Přijato"),
                            ("KN", "K navezení"),
                            ("NA", "Navezeno"),
                            ("DZ", "Do zpracování"),
                            ("ZA", "Zakaleno"),
                            ("ZK", "Zkontrolováno"),
                            ("KE", "K expedici"),
                            ("EX", "Expedováno"),
                        ],
                        max_length=2,
                        verbose_name="Stav bedny",
                    ),
                ),
                (
                    "tryskat",
                    models.CharField(
                        choices=[
                            ("--", "--------"),
                            ("CI", "Čistá"),
                            ("SP", "Špinavá"),
                            ("OT", "Otryskaná"),
                        ],
                        max_length=5,
                        verbose_name="Tryskání",
                    ),
                ),
                (
                    "rovnat",
                    models.CharField(
                        choices=[
                            ("--", "--------"),
                            ("RO", "Rovná"),
                            ("KR", "Křivá"),
                            ("RS", "Rovná se"),
                            ("VY", "Vyrovnaná"),
                        ],
                        max_length=5,
                        verbose_name="Rovnání",
                    ),
                ),
                (
                    "zinkovat",
                    models.CharField(
                        choices=[
                            ("--", "--------"),
                            ("NN", "Nezinkovat"),
                            ("KZ", "K zinkování"),
                            ("NZ", "Na zinkování"),
                            ("PZ", "Pozinkováno"),
                            ("UV", "Uvolněno"),
                        ],
                        max_length=5,
                        verbose_name="Zinkování",
                    ),
                ),
                (
                    "bedna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rozpracovanost_snapshots",
                        to="orders.bedna",
                        verbose_name="Bedna",
                    ),
                ),
                (
                    "rozpracovanost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="orders.rozpracovanost",
                        verbose_name="Rozpracovanost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot rozpracovanosti",
                "verbose_name_plural": "snapshots rozpracovanosti",
                "unique_together": {("rozpracovanost", "bedna")},
            },
        ),
        migrations.RunPython(forwards_copy_snapshot, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="rozpracovanost",
            name="bedny",
        ),
        migrations.AddField(
            model_name="rozpracovanost",
            name="bedny",
            field=models.ManyToManyField(
                related_name="rozpracovanost_zaznamy",
                through="orders.RozpracovanostBednaSnapshot",
                to="orders.bedna",
                verbose_name="Bedny",
            ),
        ),
    ]
