# Generated by Django 5.2.8 on 2026-02-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0159_rozpracovanostbednasnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rozpracovanostbednasnapshot',
            options={'verbose_name': 'Snapshot rozpracovanosti', 'verbose_name_plural': 'snapshoty rozpracovanosti'},
        ),
        migrations.AlterField(
            model_name='bedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'Zinkovat'), ('NZ', 'V zinkovně'), ('PZ', 'Pozinkováno'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'Zinkovat'), ('NZ', 'V zinkovně'), ('PZ', 'Pozinkováno'), ('UV', 'Uvolněno')], default='NN', max_length=5, verbose_name='Zinkování'),
        ),
        migrations.AlterField(
            model_name='rozpracovanostbednasnapshot',
            name='bedna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rozpracovanost_snapshots', to='orders.bedna', verbose_name='Bedna'),
        ),
        migrations.AlterField(
            model_name='rozpracovanostbednasnapshot',
            name='zinkovat',
            field=models.CharField(choices=[('--', '--------'), ('NN', 'Nezinkovat'), ('KZ', 'Zinkovat'), ('NZ', 'V zinkovně'), ('PZ', 'Pozinkováno'), ('UV', 'Uvolněno')], max_length=5, verbose_name='Zinkování'),
        ),
    ]
