# Generated by Django 5.2.8 on 2026-02-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0160_alter_rozpracovanostbednasnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodberatel',
            name='nazev',
            field=models.CharField(max_length=100, verbose_name='Název odběratele'),
        ),
        migrations.AlterField(
            model_name='historicalodberatel',
            name='zkraceny_nazev',
            field=models.CharField(help_text='Zkrácený název odběratele.', max_length=15, verbose_name='Zkrácený název'),
        ),
        migrations.AlterField(
            model_name='odberatel',
            name='nazev',
            field=models.CharField(max_length=100, verbose_name='Název odběratele'),
        ),
        migrations.AlterField(
            model_name='odberatel',
            name='zkraceny_nazev',
            field=models.CharField(help_text='Zkrácený název odběratele.', max_length=15, verbose_name='Zkrácený název'),
        ),
    ]
