# Generated by Django 5.2.8 on 2026-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0161_alter_historicalodberatel_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodberatel',
            name='zkraceny_nazev',
            field=models.CharField(db_index=True, help_text='Zkrácený název odběratele.', max_length=15, verbose_name='Zkrácený název'),
        ),
        migrations.AlterField(
            model_name='odberatel',
            name='zkraceny_nazev',
            field=models.CharField(help_text='Zkrácený název odběratele.', max_length=15, unique=True, verbose_name='Zkrácený název'),
        ),
    ]
