# Generated by Django 5.2.8 on 2026-02-16 12:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0162_alter_historicalodberatel_zkraceny_nazev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_sarze', models.PositiveIntegerField(blank=True, verbose_name='Číslo šarže')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('zacatek', models.TimeField(verbose_name='Začátek')),
                ('konec', models.TimeField(verbose_name='Konec')),
                ('operator', models.CharField(max_length=30, verbose_name='Operátor')),
                ('program', models.CharField(max_length=20, verbose_name='Program')),
                ('cislo_pripravku', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Přípravek č.')),
                ('alarm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alarm')),
            ],
            options={
                'verbose_name': 'Šarže',
                'verbose_name_plural': 'šarže',
                'ordering': ['-datum', 'zarizeni__kod_zarizeni', 'cislo_sarze'],
            },
        ),
        migrations.CreateModel(
            name='Zarizeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_zarizeni', models.CharField(max_length=10, unique=True, verbose_name='Kód zařízení')),
                ('nazev_zarizeni', models.CharField(max_length=100, verbose_name='Název zařízení')),
                ('prefix_sarze', models.CharField(max_length=3, verbose_name='Prefix šarže')),
                ('umisteni', models.CharField(blank=True, max_length=20, null=True, verbose_name='Umístění')),
                ('typ_zarizeni', models.CharField(blank=True, max_length=35, null=True, verbose_name='Typ zařízení')),
            ],
            options={
                'verbose_name': 'Zařízení',
                'verbose_name_plural': 'zařízení',
                'ordering': ['kod_zarizeni'],
            },
        ),
        migrations.CreateModel(
            name='SarzeBedna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patro', models.PositiveSmallIntegerField(verbose_name='Patro')),
                ('procent_z_patra', models.DecimalField(decimal_places=2, help_text='Podíl využití patra pro danou bednu (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='% z patra')),
                ('poznamka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka')),
                ('bedna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sarze_bedny', to='orders.bedna', verbose_name='Bedna')),
                ('sarze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarze_bedny', to='orders.sarze', verbose_name='Šarže')),
            ],
            options={
                'verbose_name': 'Šarže - bedna',
                'verbose_name_plural': 'šarže - bedny',
                'ordering': ['sarze_id', 'patro', 'bedna_id'],
            },
        ),
        migrations.AddField(
            model_name='sarze',
            name='bedny',
            field=models.ManyToManyField(related_name='sarze_zarizeni', through='orders.SarzeBedna', to='orders.bedna', verbose_name='Bedny'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='zarizeni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sarze', to='orders.zarizeni', verbose_name='Zařízení'),
        ),
        migrations.AddConstraint(
            model_name='sarzebedna',
            constraint=models.UniqueConstraint(fields=('sarze', 'bedna', 'patro'), name='uniq_sarze_bedna_patro'),
        ),
        migrations.AddConstraint(
            model_name='sarze',
            constraint=models.UniqueConstraint(fields=('zarizeni', 'cislo_sarze'), name='uniq_sarze_zarizeni'),
        ),
    ]
