# Generated by Django 5.2.8 on 2026-02-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0163_sarze_zarizeni_sarzebedna_sarze_bedny_sarze_zarizeni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarzebedna',
            options={'ordering': ['sarze_id', 'patro', 'bedna_id'], 'verbose_name': 'Bedna v šarži', 'verbose_name_plural': 'bedny v šarži'},
        ),
    ]
