# Generated by Django 5.2.8 on 2026-02-16 12:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0164_alter_sarzebedna_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarzebedna',
            options={'ordering': ['sarze_id', 'patro', 'bedna_id'], 'verbose_name': 'Bedna v šarži', 'verbose_name_plural': 'deník pece'},
        ),
        migrations.AlterField(
            model_name='sarzebedna',
            name='procent_z_patra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Podíl využití patra pro danou bednu (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='% z patra'),
        ),
    ]
