# Generated by Django 5.2.8 on 2026-02-17 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0165_alter_sarzebedna_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarzebedna',
            name='procent_z_patra',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Podíl využití patra pro danou bednu (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procent z patra'),
        ),
    ]
