# Generated by Django 5.2.8 on 2026-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0166_alter_sarzebedna_procent_z_patra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarze',
            name='cislo_pripravku',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku'),
        ),
    ]
