# Generated by Django 5.2.8 on 2026-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0167_alter_sarze_cislo_pripravku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarze',
            name='konec',
            field=models.TimeField(blank=True, null=True, verbose_name='Konec'),
        ),
    ]
