# Generated by Django 5.2.8 on 2026-02-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0168_alter_sarze_konec'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarizeni',
            name='zkraceny_nazev_zarizeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zkrácený název'),
        ),
    ]
