# Generated by Django 5.2.8 on 2026-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0169_zarizeni_zkraceny_nazev_zarizeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarizeni',
            name='zkraceny_nazev_zarizeni',
            field=models.CharField(max_length=50, verbose_name='Zkrácený název'),
        ),
    ]
