# Generated by Django 5.2.8 on 2026-02-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0170_alter_zarizeni_zkraceny_nazev_zarizeni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarzebedna',
            name='poznamka',
        ),
        migrations.AddField(
            model_name='sarze',
            name='poznamka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka'),
        ),
    ]
