# Generated by Django 5.2.8 on 2026-02-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0171_remove_sarzebedna_poznamka_sarze_poznamka'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarzebedna',
            name='bedna_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bedna (text)'),
        ),
        migrations.AlterField(
            model_name='sarzebedna',
            name='bedna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarze_bedny', to='orders.bedna', verbose_name='Bedna'),
        ),
    ]
