# Generated by Django 5.2.8 on 2026-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0172_sarzebedna_bedna_text_alter_sarzebedna_bedna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarzebedna',
            name='bedna_text',
        ),
        migrations.AddField(
            model_name='sarzebedna',
            name='popis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Popis'),
        ),
    ]
