# Generated by Django 5.2.8 on 2026-02-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0173_remove_sarzebedna_bedna_text_sarzebedna_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarzebedna',
            name='bedna',
            field=models.ForeignKey(blank=True, help_text='Při zpracování vrutů vyberte bednu z databáze.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarze_bedny', to='orders.bedna', verbose_name='Bedna'),
        ),
        migrations.AlterField(
            model_name='sarzebedna',
            name='popis',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte popis zakázky.', max_length=50, null=True, verbose_name='Popis'),
        ),
    ]
