# Generated by Django 5.2.8 on 2026-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0174_alter_sarzebedna_bedna_alter_sarzebedna_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarzebedna',
            name='zakaznik_mimo_db',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte název zákazníka, který není v databázi.', max_length=50, null=True, verbose_name='Zákazník "železo"'),
        ),
    ]
