# Generated by Django 5.2.8 on 2026-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0175_sarzebedna_zakaznik_mimo_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarzebedna',
            name='popis',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte popis zakázky.', max_length=50, null=True, verbose_name='Popis pro "železo"'),
        ),
        migrations.AlterField(
            model_name='sarzebedna',
            name='zakaznik_mimo_db',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte název zákazníka.', max_length=50, null=True, verbose_name='Zákazník pro "železo"'),
        ),
    ]
