# Generated by Django 5.2.8 on 2026-02-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0176_alter_sarzebedna_popis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarzebedna',
            name='zakazka_mimo_db',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte zakázku.', max_length=30, null=True, verbose_name='Zakázka pro "železo"'),
        ),
    ]
