# Generated by Django 5.2.8 on 2026-02-18 13:06

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0177_sarzebedna_zakazka_mimo_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSarze',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo_sarze', models.PositiveIntegerField(blank=True, verbose_name='Číslo šarže')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('zacatek', models.TimeField(verbose_name='Začátek')),
                ('konec', models.TimeField(blank=True, null=True, verbose_name='Konec')),
                ('operator', models.CharField(max_length=30, verbose_name='Operátor')),
                ('program', models.CharField(max_length=20, verbose_name='Program')),
                ('cislo_pripravku', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku')),
                ('poznamka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka')),
                ('alarm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alarm')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zarizeni', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.zarizeni', verbose_name='Zařízení')),
            ],
            options={
                'verbose_name': 'historical Šarže',
                'verbose_name_plural': 'historical šarže',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSarzeBedna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('popis', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte popis zakázky.', max_length=50, null=True, verbose_name='Popis pro "železo"')),
                ('zakaznik_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte název zákazníka.', max_length=50, null=True, verbose_name='Zákazník pro "železo"')),
                ('zakazka_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte zakázku.', max_length=30, null=True, verbose_name='Zakázka pro "železo"')),
                ('patro', models.PositiveSmallIntegerField(verbose_name='Patro')),
                ('procent_z_patra', models.PositiveSmallIntegerField(blank=True, help_text='Podíl využití patra pro danou bednu (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procent z patra')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bedna', models.ForeignKey(blank=True, db_constraint=False, help_text='Při zpracování vrutů vyberte bednu z databáze.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.bedna', verbose_name='Bedna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sarze', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.sarze', verbose_name='Šarže')),
            ],
            options={
                'verbose_name': 'historical Bedna v šarži',
                'verbose_name_plural': 'historical deník pece',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalZarizeni',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kod_zarizeni', models.CharField(db_index=True, max_length=10, verbose_name='Kód zařízení')),
                ('nazev_zarizeni', models.CharField(max_length=100, verbose_name='Název zařízení')),
                ('zkraceny_nazev_zarizeni', models.CharField(max_length=50, verbose_name='Zkrácený název')),
                ('prefix_sarze', models.CharField(max_length=3, verbose_name='Prefix šarže')),
                ('umisteni', models.CharField(blank=True, max_length=20, null=True, verbose_name='Umístění')),
                ('typ_zarizeni', models.CharField(blank=True, max_length=35, null=True, verbose_name='Typ zařízení')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Zařízení',
                'verbose_name_plural': 'historical zařízení',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
