# Generated by Django 5.2.8 on 2026-02-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0178_historicalsarze_historicalsarzebedna_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Zpráva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Přečteno')),
                ('ack_required', models.BooleanField(default=True, verbose_name='Vyžaduje potvrzení')),
                ('ack_at', models.DateTimeField(blank=True, null=True, verbose_name='Potvrzeno')),
                ('ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Potvrdil')),
                ('bedna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_notifications', to='orders.bedna', verbose_name='Bedna')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Příjemce')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_notifications', to='orders.zakazka', verbose_name='Zakázka')),
            ],
            options={
                'verbose_name': 'Notifikace',
                'verbose_name_plural': 'notifikace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriorityNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Výchozí příjemci', max_length=50, verbose_name='Název')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('groups', models.ManyToManyField(blank=True, related_name='priority_notification_recipients', to='auth.group', verbose_name='Skupiny')),
                ('users', models.ManyToManyField(blank=True, related_name='priority_notification_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelé')),
            ],
            options={
                'verbose_name': 'Příjemci notifikací priority',
                'verbose_name_plural': 'příjemci notifikací priority',
            },
        ),
    ]
