# Generated by Django 5.2.8 on 2026-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0179_notification_prioritynotificationrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('PRIORITA', 'Změna priority')], default='PRIORITA', max_length=20, verbose_name='Typ notifikace'),
        ),
    ]
