# Generated by Django 5.2.8 on 2026-02-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0180_notification_notif_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
    ]
