# Generated by Django 5.2.8 on 2026-02-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0181_remove_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarzebedna',
            name='cislo_bedny_mimo_db',
            field=models.PositiveIntegerField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', null=True, verbose_name='Číslo bedny pro "železo"'),
        ),
        migrations.AddField(
            model_name='sarzebedna',
            name='cislo_bedny_mimo_db',
            field=models.PositiveIntegerField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', null=True, verbose_name='Číslo bedny pro "železo"'),
        ),
    ]
