# Generated by Django 5.2.8 on 2026-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0182_historicalsarzebedna_cislo_bedny_mimo_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsarzebedna',
            name='cislo_bedny_mimo_db',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', max_length=30, null=True, verbose_name='Číslo bedny pro "železo"'),
        ),
        migrations.AlterField(
            model_name='sarzebedna',
            name='cislo_bedny_mimo_db',
            field=models.CharField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', max_length=30, null=True, verbose_name='Číslo bedny pro "železo"'),
        ),
    ]
