# Generated by Django 5.2.8 on 2026-02-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0183_alter_historicalsarzebedna_cislo_bedny_mimo_db_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarze',
            options={'ordering': ['-datum', 'zarizeni__kod_zarizeni', 'cislo_sarze'], 'permissions': [('can_move_sarze', 'Může přesouvat šarže mezi zařízeními')], 'verbose_name': 'Šarže', 'verbose_name_plural': 'šarže'},
        ),
    ]
