# Generated by Django 5.2.8 on 2026-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0184_alter_sarze_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='rovnat',
            field=models.CharField(choices=[('--', '--------'), ('RO', 'Rovná'), ('KR', 'Křivá'), ('KO', 'Koulení'), ('RS', 'Rovná se'), ('VY', 'Vyrovnaná')], default='--', max_length=5, verbose_name='Rovnání'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='rovnat',
            field=models.CharField(choices=[('--', '--------'), ('RO', 'Rovná'), ('KR', 'Křivá'), ('KO', 'Koulení'), ('RS', 'Rovná se'), ('VY', 'Vyrovnaná')], default='--', max_length=5, verbose_name='Rovnání'),
        ),
        migrations.AlterField(
            model_name='rozpracovanostbednasnapshot',
            name='rovnat',
            field=models.CharField(choices=[('--', '--------'), ('RO', 'Rovná'), ('KR', 'Křivá'), ('KO', 'Koulení'), ('RS', 'Rovná se'), ('VY', 'Vyrovnaná')], max_length=5, verbose_name='Rovnání'),
        ),
    ]
