# Generated by Django 5.2.8 on 2026-03-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0185_alter_bedna_rovnat_alter_historicalbedna_rovnat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozicezakazkaorder',
            name='poznamka_k_navezeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poznámka k navezení'),
        ),
    ]
