# Generated by Django 5.2.8 on 2026-03-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0186_pozicezakazkaorder_poznamka_k_navezeni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedna',
            name='poznamka_k_navezeni',
        ),
        migrations.RemoveField(
            model_name='historicalbedna',
            name='poznamka_k_navezeni',
        ),
    ]
