# Generated by Django 5.2.8 on 2026-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0187_remove_bedna_poznamka_k_navezeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozicezakazkaorder',
            name='nasledne',
            field=models.BooleanField(default=False, verbose_name='Následně?'),
        ),
    ]
