# Generated by Django 5.2.8 on 2026-03-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0188_pozicezakazkaorder_nasledne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazka',
            name='kamion_prijem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazky_prijem', to='orders.kamion', verbose_name='Kamión příjem'),
        ),
    ]
