# Generated by Django 5.2.8 on 2026-03-12 10:56

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0189_alter_zakazka_kamion_prijem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kamion',
            constraint=models.UniqueConstraint(models.F('zakaznik'), models.F('prijem_vydej'), django.db.models.functions.datetime.ExtractYear('datum'), models.F('poradove_cislo'), name='uniq_kamion_poradove_per_year'),
        ),
    ]
