# Generated by Django 5.2.13 on 2026-05-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0190_kamion_uniq_kamion_poradove_per_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={'ordering': ['id'], 'permissions': (('change_expedovana_bedna', 'Může upravovat expedované bedny'), ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny'), ('change_neprijata_bedna', 'Může upravovat bedny ve stavu NEPŘIJATO'), ('change_poznamka_neprijata_bedna', 'Může upravovat poznámku u bedny ve stavu NEPŘIJATO'), ('mark_bedna_navezeno', 'Může označit bednu jako navezenou a vrátit ji zpět na příjem'), ('mark_bedna_zakaleno', 'Může označit bednu jako zakalenou přímo z příjmu (např. při reklamaci)')), 'verbose_name': 'Bedna', 'verbose_name_plural': 'bedny'},
        ),
    ]
