# Generated by Django 5.2.13 on 2026-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0191_alter_bedna_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzakazka',
            name='celozavit',
            field=models.BooleanField(default=False, verbose_name='VG'),
        ),
        migrations.AlterField(
            model_name='zakazka',
            name='celozavit',
            field=models.BooleanField(default=False, verbose_name='VG'),
        ),
    ]
