# Generated by Django 5.2.13 on 2026-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0192_alter_historicalzakazka_celozavit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozice',
            name='poznamka_k_pozici',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka k pozici'),
        ),
    ]
