# Generated by Django 5.2.13 on 2026-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0193_pozice_poznamka_k_pozici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozice',
            name='poznamka_k_pozici',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka k pozici'),
        ),
    ]
