# Generated by Django 5.2.13 on 2026-05-18 00:00

from django.db import migrations, models


def map_typ_zarizeni_forward(apps, schema_editor):
    Zarizeni = apps.get_model('orders', 'Zarizeni')
    HistoricalZarizeni = apps.get_model('orders', 'HistoricalZarizeni')

    mapping = {
        'Víceúčelová pec': 'VU',
        'Víceucelova pec': 'VU',
        'Popouštěcí pec': 'PP',
        'Popousteci pec': 'PP',
    }

    for old_value, new_value in mapping.items():
        Zarizeni.objects.filter(typ_zarizeni=old_value).update(typ_zarizeni=new_value)
        HistoricalZarizeni.objects.filter(typ_zarizeni=old_value).update(typ_zarizeni=new_value)


def map_typ_zarizeni_backward(apps, schema_editor):
    Zarizeni = apps.get_model('orders', 'Zarizeni')
    HistoricalZarizeni = apps.get_model('orders', 'HistoricalZarizeni')

    reverse_mapping = {
        'VU': 'Víceúčelová pec',
        'PP': 'Popouštěcí pec',
    }

    for old_value, new_value in reverse_mapping.items():
        Zarizeni.objects.filter(typ_zarizeni=old_value).update(typ_zarizeni=new_value)
        HistoricalZarizeni.objects.filter(typ_zarizeni=old_value).update(typ_zarizeni=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0194_alter_pozice_poznamka_k_pozici'),
    ]

    operations = [
        migrations.RunPython(map_typ_zarizeni_forward, map_typ_zarizeni_backward),
        migrations.AlterField(
            model_name='historicalzarizeni',
            name='typ_zarizeni',
            field=models.CharField(
                blank=True,
                choices=[
                    ('VU', 'Víceúčelová pec'),
                    ('PP', 'Popouštěcí pec'),
                    ('PR', 'Pračka'),
                    ('TR', 'Tryskač'),
                    ('PD', 'Předehřev'),
                ],
                max_length=2,
                null=True,
                verbose_name='Typ zařízení',
            ),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='typ_zarizeni',
            field=models.CharField(
                blank=True,
                choices=[
                    ('VU', 'Víceúčelová pec'),
                    ('PP', 'Popouštěcí pec'),
                    ('PR', 'Pračka'),
                    ('TR', 'Tryskač'),
                    ('PD', 'Předehřev'),
                ],
                max_length=2,
                null=True,
                verbose_name='Typ zařízení',
            ),
        ),
    ]
