# Generated by Django 5.2.13 on 2026-05-18 08:43

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0195_typ_zarizeni_choices_and_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSarzeKrok',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poradi', models.PositiveIntegerField(verbose_name='Pořadí')),
                ('zacatek', models.TimeField(verbose_name='Začátek')),
                ('konec', models.TimeField(blank=True, null=True, verbose_name='Konec')),
                ('operator', models.CharField(max_length=30, verbose_name='Operátor')),
                ('program', models.CharField(blank=True, max_length=20, null=True, verbose_name='Program')),
                ('cislo_pripravku', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku')),
                ('alarm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alarm')),
                ('poznamka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Krok šarže',
                'verbose_name_plural': 'historical kroky šarže',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSarzeKrokBedna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('popis_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte popis zakázky.', max_length=50, null=True, verbose_name='Popis mimo DB')),
                ('zakaznik_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte název zákazníka.', max_length=50, null=True, verbose_name='Zákazník mimo DB')),
                ('zakazka_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte zakázku.', max_length=30, null=True, verbose_name='Zakázka mimo DB')),
                ('cislo_bedny_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', max_length=30, null=True, verbose_name='Číslo bedny mimo DB')),
                ('patro', models.PositiveSmallIntegerField(verbose_name='Patro')),
                ('procent_z_patra', models.PositiveSmallIntegerField(blank=True, help_text='Podíl využití patra pro danou bednu (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procent z patra')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Bedna v kroku šarže',
                'verbose_name_plural': 'historical deník pece',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SarzeKrok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.PositiveIntegerField(verbose_name='Pořadí')),
                ('zacatek', models.TimeField(verbose_name='Začátek')),
                ('konec', models.TimeField(blank=True, null=True, verbose_name='Konec')),
                ('operator', models.CharField(max_length=30, verbose_name='Operátor')),
                ('program', models.CharField(blank=True, max_length=20, null=True, verbose_name='Program')),
                ('cislo_pripravku', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku')),
                ('alarm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alarm')),
                ('poznamka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Krok šarže',
                'verbose_name_plural': 'kroky šarže',
                'ordering': ['sarze_id', 'poradi'],
            },
        ),
        migrations.CreateModel(
            name='SarzeKrokBedna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte popis zakázky.', max_length=50, null=True, verbose_name='Popis mimo DB')),
                ('zakaznik_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte název zákazníka.', max_length=50, null=True, verbose_name='Zákazník mimo DB')),
                ('zakazka_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte zakázku.', max_length=30, null=True, verbose_name='Zakázka mimo DB')),
                ('cislo_bedny_mimo_db', models.CharField(blank=True, help_text='Při zpracování "železa" zadejte číslo bedny.', max_length=30, null=True, verbose_name='Číslo bedny mimo DB')),
                ('patro', models.PositiveSmallIntegerField(verbose_name='Patro')),
                ('procent_z_patra', models.PositiveSmallIntegerField(blank=True, help_text='Podíl využití patra pro danou bednu (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procent z patra')),
            ],
            options={
                'verbose_name': 'Bedna v kroku šarže',
                'verbose_name_plural': 'deník pece',
                'ordering': ['krok_id', 'patro', 'bedna_id'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalsarzebedna',
            name='bedna',
        ),
        migrations.RemoveField(
            model_name='historicalsarzebedna',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsarzebedna',
            name='sarze',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='bedny',
        ),
        migrations.AlterModelOptions(
            name='sarze',
            options={'ordering': ['-datum_zalozeni', '-cislo_sarze'], 'verbose_name': 'Šarže', 'verbose_name_plural': 'šarže'},
        ),
        migrations.RemoveConstraint(
            model_name='sarze',
            name='uniq_sarze_zarizeni',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='cislo_pripravku',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='konec',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='zacatek',
        ),
        migrations.RemoveField(
            model_name='historicalsarze',
            name='zarizeni',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='cislo_pripravku',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='konec',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='program',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='zacatek',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='zarizeni',
        ),
        migrations.AddField(
            model_name='historicalsarze',
            name='aktivni',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AddField(
            model_name='historicalsarze',
            name='datum_zalozeni',
            field=models.DateField(default=datetime.date(2026, 5, 18), verbose_name='Datum založení'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sarze',
            name='aktivni',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='datum_zalozeni',
            field=models.DateField(default=datetime.date(2026, 5, 18), verbose_name='Datum založení'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='sarze',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.sarze', verbose_name='Šarže'),
        ),
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='zarizeni',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.zarizeni', verbose_name='Zařízení'),
        ),
        migrations.AddField(
            model_name='historicalsarzekrokbedna',
            name='bedna',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Při zpracování vrutů vyberte bednu z databáze.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.bedna', verbose_name='Bedna'),
        ),
        migrations.AddField(
            model_name='historicalsarzekrokbedna',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sarzekrok',
            name='sarze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kroky', to='orders.sarze', verbose_name='Šarže'),
        ),
        migrations.AddField(
            model_name='sarzekrok',
            name='zarizeni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sarze_kroky', to='orders.zarizeni', verbose_name='Zařízení'),
        ),
        migrations.AddField(
            model_name='historicalsarzekrokbedna',
            name='krok',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.sarzekrok', verbose_name='Krok šarže'),
        ),
        migrations.AddField(
            model_name='sarzekrokbedna',
            name='bedna',
            field=models.ForeignKey(blank=True, help_text='Při zpracování vrutů vyberte bednu z databáze.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarze_krok_bedny', to='orders.bedna', verbose_name='Bedna'),
        ),
        migrations.AddField(
            model_name='sarzekrokbedna',
            name='krok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krok_bedny', to='orders.sarzekrok', verbose_name='Krok šarže'),
        ),
        migrations.DeleteModel(
            name='HistoricalSarzeBedna',
        ),
        migrations.DeleteModel(
            name='SarzeBedna',
        ),
        migrations.AddConstraint(
            model_name='sarzekrok',
            constraint=models.UniqueConstraint(fields=('sarze', 'poradi'), name='uniq_sarzekrok_sarze_poradi'),
        ),
        migrations.AddConstraint(
            model_name='sarzekrokbedna',
            constraint=models.UniqueConstraint(fields=('krok', 'bedna', 'patro'), name='uniq_sarzekrokbedna_krok_bedna_patro'),
        ),
        migrations.AddConstraint(
            model_name='sarzekrokbedna',
            constraint=models.CheckConstraint(condition=models.Q(('procent_z_patra__isnull', True), models.Q(('procent_z_patra__gte', 0), ('procent_z_patra__lte', 100)), _connector='OR'), name='ck_sarzekrokbedna_procent_0_100'),
        ),
    ]
