# Generated by Django 5.2.13 on 2026-05-18 12:50

from django.db import migrations, models


def forward_fill_sarze_and_krok_fields(apps, schema_editor):
    Sarze = apps.get_model('orders', 'Sarze')
    SarzeKrok = apps.get_model('orders', 'SarzeKrok')

    # Nové datum kroku naplníme původním datem založení šarže.
    for krok in SarzeKrok.objects.filter(datum__isnull=True).select_related('sarze'):
        if krok.sarze_id and krok.sarze and krok.sarze.datum_zalozeni:
            krok.datum = krok.sarze.datum_zalozeni
            krok.save(update_fields=['datum'])

    # Číslo přípravku přesuneme na šarži z prvního nenulového kroku dané šarže.
    for sarze in Sarze.objects.filter(cislo_pripravku__isnull=True):
        prvni_krok_s_pripravkem = (
            SarzeKrok.objects
            .filter(sarze_id=sarze.id, cislo_pripravku__isnull=False)
            .order_by('poradi', 'id')
            .first()
        )
        if prvni_krok_s_pripravkem:
            sarze.cislo_pripravku = prvni_krok_s_pripravkem.cislo_pripravku
            sarze.save(update_fields=['cislo_pripravku'])


def backward_fill_krok_cislo_pripravku(apps, schema_editor):
    SarzeKrok = apps.get_model('orders', 'SarzeKrok')

    # Při rollbacku vrátíme hodnotu z šarže do kroku, pokud krok žádnou nemá.
    for krok in SarzeKrok.objects.filter(cislo_pripravku__isnull=True).select_related('sarze'):
        if krok.sarze_id and krok.sarze and krok.sarze.cislo_pripravku is not None:
            krok.cislo_pripravku = krok.sarze.cislo_pripravku
            krok.save(update_fields=['cislo_pripravku'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0196_historicalsarzekrok_historicalsarzekrokbedna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarze',
            name='cislo_pripravku',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku'),
        ),
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='cislo_pripravku',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Číslo přípravku'),
        ),
        migrations.AddField(
            model_name='sarzekrok',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.RunPython(forward_fill_sarze_and_krok_fields, backward_fill_krok_cislo_pripravku),
        migrations.RemoveField(
            model_name='historicalsarzekrok',
            name='cislo_pripravku',
        ),
        migrations.RemoveField(
            model_name='sarzekrok',
            name='cislo_pripravku',
        ),
    ]
