# Generated by Django 5.2.13 on 2026-05-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0197_remove_historicalsarzekrok_cislo_pripravku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarzekrok',
            name='zarizeni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarze_kroky', to='orders.zarizeni', verbose_name='Zařízení'),
        ),
    ]
