# Generated by Django 5.2.13 on 2026-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0198_alter_sarzekrok_zarizeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='operator',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Operátor'),
        ),
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='zacatek',
            field=models.TimeField(blank=True, null=True, verbose_name='Začátek'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='operator',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Operátor'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='zacatek',
            field=models.TimeField(blank=True, null=True, verbose_name='Začátek'),
        ),
    ]
