# Generated by Django 5.2.13 on 2026-05-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0199_alter_historicalsarzekrok_operator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalzarizeni',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pracoviště', 'verbose_name_plural': 'historical pracoviště'},
        ),
        migrations.AlterModelOptions(
            name='zarizeni',
            options={'ordering': ['kod_zarizeni'], 'verbose_name': 'Pracoviště', 'verbose_name_plural': 'pracoviště'},
        ),
        migrations.RemoveField(
            model_name='historicalzarizeni',
            name='prefix_sarze',
        ),
        migrations.RemoveField(
            model_name='zarizeni',
            name='prefix_sarze',
        ),
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='zarizeni',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.zarizeni', verbose_name='Pracoviště'),
        ),
        migrations.AlterField(
            model_name='historicalzarizeni',
            name='kod_zarizeni',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Kód pracoviště'),
        ),
        migrations.AlterField(
            model_name='historicalzarizeni',
            name='nazev_zarizeni',
            field=models.CharField(max_length=100, verbose_name='Název pracoviště'),
        ),
        migrations.AlterField(
            model_name='historicalzarizeni',
            name='typ_zarizeni',
            field=models.CharField(blank=True, choices=[('VU', 'Víceúčelová pec'), ('PP', 'Popouštěcí pec'), ('PR', 'Pračka'), ('TR', 'Tryskač'), ('PD', 'Předehřev'), ('SZ', 'Šaržování')], max_length=2, null=True, verbose_name='Typ pracoviště'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='zarizeni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarze_kroky', to='orders.zarizeni', verbose_name='Pracoviště'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='kod_zarizeni',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kód pracoviště'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='nazev_zarizeni',
            field=models.CharField(max_length=100, verbose_name='Název pracoviště'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='typ_zarizeni',
            field=models.CharField(blank=True, choices=[('VU', 'Víceúčelová pec'), ('PP', 'Popouštěcí pec'), ('PR', 'Pračka'), ('TR', 'Tryskač'), ('PD', 'Předehřev'), ('SZ', 'Šaržování')], max_length=2, null=True, verbose_name='Typ pracoviště'),
        ),
    ]
