# Generated by Django 5.2.13 on 2026-05-25 08:59

import django.db.models.deletion
from django.db import migrations, models
import datetime


def _fill_sarzekrok_required_fields(apps, schema_editor):
    SarzeKrok = apps.get_model('orders', 'SarzeKrok')
    HistoricalSarzeKrok = apps.get_model('orders', 'HistoricalSarzeKrok')
    Zarizeni = apps.get_model('orders', 'Zarizeni')

    fallback_zarizeni = Zarizeni.objects.order_by('pk').first()
    if fallback_zarizeni is None:
        fallback_zarizeni, _ = Zarizeni.objects.get_or_create(
            kod_zarizeni='MIG',
            defaults={
                'nazev_zarizeni': 'Migrační pracoviště',
                'zkraceny_nazev_zarizeni': 'MIG',
            },
        )

    SarzeKrok.objects.filter(operator__isnull=True).update(operator='MIGRACE')
    SarzeKrok.objects.filter(zacatek__isnull=True).update(zacatek=datetime.time(0, 0))
    SarzeKrok.objects.filter(zarizeni__isnull=True).update(zarizeni_id=fallback_zarizeni.pk)

    HistoricalSarzeKrok.objects.filter(operator__isnull=True).update(operator='MIGRACE')
    HistoricalSarzeKrok.objects.filter(zacatek__isnull=True).update(zacatek=datetime.time(0, 0))


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # PostgreSQL: data update + ALTER TABLE over the same table in one transaction
    # can fail with "cannot ALTER TABLE ... because it has pending trigger events".
    atomic = False

    dependencies = [
        ('orders', '0200_alter_historicalzarizeni_options_and_more'),
    ]

    operations = [
        migrations.RunPython(_fill_sarzekrok_required_fields, _noop_reverse),
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='operator',
            field=models.CharField(max_length=30, verbose_name='Operátor'),
        ),
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='zacatek',
            field=models.TimeField(verbose_name='Začátek'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='operator',
            field=models.CharField(max_length=30, verbose_name='Operátor'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='zacatek',
            field=models.TimeField(verbose_name='Začátek'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='zarizeni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sarze_kroky', to='orders.zarizeni', verbose_name='Pracoviště'),
        ),
    ]
