# Generated by Django 5.2.13 on 2026-05-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0201_alter_historicalsarzekrokbedna_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsarzekrokbedna',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bedna v kroku šarže', 'verbose_name_plural': 'historical deník'},
        ),
        migrations.AlterModelOptions(
            name='sarzekrokbedna',
            options={'ordering': ['krok_id', 'patro', 'bedna_id'], 'verbose_name': 'Bedna v kroku šarže', 'verbose_name_plural': 'deník'},
        ),
    ]
