# Generated by Django 5.2.13 on 2026-05-28 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0202_alter_historicalsarzekrokbedna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpletivo',
            name='pocet_vrutu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet vrutů'),
        ),
        migrations.AddField(
            model_name='pletivo',
            name='pocet_vrutu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet vrutů'),
        ),
    ]
