# Generated by Django 5.2.13 on 2026-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0203_historicalpletivo_pocet_vrutu_pletivo_pocet_vrutu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='action_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, verbose_name='Token akce'),
        ),
        migrations.AddField(
            model_name='sarzekrok',
            name='action_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Token akce'),
        ),
    ]
