# Generated by Django 5.2.13 on 2026-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0204_historicalsarzekrok_action_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzarizeni',
            name='typ_zarizeni',
            field=models.CharField(blank=True, choices=[('VU', 'Víceúčelová pec'), ('PP', 'Popouštěcí pec'), ('PR', 'Pračka'), ('TR', 'Tryskač'), ('PD', 'Předehřev'), ('NK', 'Nakládání'), ('VK', 'Vykládání')], max_length=2, null=True, verbose_name='Typ pracoviště'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='typ_zarizeni',
            field=models.CharField(blank=True, choices=[('VU', 'Víceúčelová pec'), ('PP', 'Popouštěcí pec'), ('PR', 'Pračka'), ('TR', 'Tryskač'), ('PD', 'Předehřev'), ('NK', 'Nakládání'), ('VK', 'Vykládání')], max_length=2, null=True, verbose_name='Typ pracoviště'),
        ),
    ]
