# Generated by Django 5.2.13 on 2026-06-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0205_alter_historicalzarizeni_typ_zarizeni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarzekrokbedna',
            options={'ordering': ['krok_id', 'patro', 'pk'], 'verbose_name': 'Bedna v kroku šarže', 'verbose_name_plural': 'deník'},
        ),
        migrations.RemoveConstraint(
            model_name='sarzekrokbedna',
            name='uniq_sarzekrokbedna_krok_bedna_patro',
        ),
    ]
