# Generated by Django 5.2.13 on 2026-07-02 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0206_alter_sarzekrokbedna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarze',
            name='cislo_pracoviste',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Číslo pracoviště'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='cislo_pracoviste',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Číslo pracoviště'),
        ),
    ]
