# Generated by Django 5.2.13 on 2026-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0208_alter_sarzekrokbedna_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedna',
            name='stav_bedny',
            field=models.CharField(choices=[('NE', 'Nepřijato'), ('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Ve zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='NE', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='historicalbedna',
            name='stav_bedny',
            field=models.CharField(choices=[('NE', 'Nepřijato'), ('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Ve zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], default='NE', max_length=2, verbose_name='Stav bedny'),
        ),
        migrations.AlterField(
            model_name='rozpracovanostbednasnapshot',
            name='stav_bedny',
            field=models.CharField(choices=[('NE', 'Nepřijato'), ('PR', 'Přijato'), ('KN', 'K navezení'), ('NA', 'Navezeno'), ('DZ', 'Ve zpracování'), ('ZA', 'Zakaleno'), ('ZK', 'Zkontrolováno'), ('KE', 'K expedici'), ('EX', 'Expedováno')], max_length=2, verbose_name='Stav bedny'),
        ),
    ]
