# Generated by Django 5.2.13 on 2026-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0210_alter_bedna_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarze',
            name='stav_sarze',
            field=models.CharField(choices=[('VY', 'Vytvořená'), ('PL', 'Zaplánovaná'), ('NL', 'Naložená'), ('VK', 'Vyložená ke kontrole'), ('ZK', 'Zakalená ke kontrole'), ('ZV', 'Zkontrolovaná k vyložení'), ('UK', 'Ukončená'), ('PO', 'Pozastavená'), ('ZR', 'Zrušená')], default='VY', max_length=2, verbose_name='Stav šarže'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='stav_sarze',
            field=models.CharField(choices=[('VY', 'Vytvořená'), ('PL', 'Zaplánovaná'), ('NL', 'Naložená'), ('VK', 'Vyložená ke kontrole'), ('ZK', 'Zakalená ke kontrole'), ('ZV', 'Zkontrolovaná k vyložení'), ('UK', 'Ukončená'), ('PO', 'Pozastavená'), ('ZR', 'Zrušená')], default='VY', max_length=2, verbose_name='Stav šarže'),
        ),
    ]
