# Generated by Django 5.2.13 on 2026-08-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0211_historicalsarze_stav_sarze_sarze_stav_sarze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarze',
            options={'ordering': ['-datum_zalozeni', '-cislo_sarze'], 'permissions': (('change_stav_sarze_operator', 'Může měnit stav šarže jako operátor'), ('change_stav_sarze_kontrolor', 'Může měnit stav šarže jako kontrolor')), 'verbose_name': 'Šarže', 'verbose_name_plural': 'šarže'},
        ),
    ]
