# Generated by Codex on 2026-08-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0212_alter_sarze_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarze',
            options={
                'ordering': ['-datum_zalozeni', '-cislo_sarze'],
                'permissions': (
                    ('can_move_sarze', 'Může přesouvat šarže mezi kroky'),
                    ('change_stav_sarze_operator', 'Může měnit stav šarže jako operátor'),
                    ('change_stav_sarze_kontrolor', 'Může měnit stav šarže jako kontrolor'),
                ),
                'verbose_name': 'Šarže',
                'verbose_name_plural': 'šarže',
            },
        ),
    ]
