# Generated by Codex on 2026-08-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0213_alter_sarze_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedna',
            options={
                'ordering': ['id'],
                'permissions': (
                    ('change_expedovana_bedna', 'Může upravovat expedované bedny'),
                    ('change_pozastavena_bedna', 'Může upravovat a uvolnit pozastavené bedny'),
                    ('change_neprijata_bedna', 'Může upravovat bedny ve stavu NEPŘIJATO'),
                    ('change_poznamka_neprijata_bedna', 'Může upravovat poznámku u bedny ve stavu NEPŘIJATO'),
                    ('mark_bedna_navezeno', 'Může označit bednu jako navezenou a vrátit ji zpět na příjem'),
                    ('mark_bedna_zakaleno', 'Může označit bednu jako zakalenou přes skenování'),
                    ('mark_bedna_zkontrolovano', 'Může označit bednu jako zkontrolovanou přes skenování'),
                ),
                'verbose_name': 'Bedna',
                'verbose_name_plural': 'bedny',
            },
        ),
    ]
