# Generated by Django 5.2.13 on 2026-08-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0214_alter_bedna_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsarze',
            name='aktivni',
        ),
        migrations.RemoveField(
            model_name='sarze',
            name='aktivni',
        ),
    ]
