# Generated by Django 5.2.17 on 2026-08-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0216_alter_bedna_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarze',
            name='popousteni',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Popouštění'),
        ),
        migrations.AddField(
            model_name='sarze',
            name='popousteni',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Popouštění'),
        ),
    ]
