# Generated by Django 5.2.17 on 2026-08-20 11:49

from datetime import timedelta

from django.db import migrations, models


def doplnit_datum_konce(apps, schema_editor):
    for model_name in ('SarzeKrok', 'HistoricalSarzeKrok'):
        model = apps.get_model('orders', model_name)
        model.objects.filter(
            konec__isnull=False,
            datum_konce__isnull=True,
        ).update(datum_konce=models.F('datum'))
        model.objects.filter(
            konec__isnull=False,
            zacatek__isnull=False,
            datum_konce__isnull=False,
            konec__lt=models.F('zacatek'),
        ).update(datum_konce=models.F('datum_konce') + timedelta(days=1))


def odebrat_datum_konce(apps, schema_editor):
    for model_name in ('SarzeKrok', 'HistoricalSarzeKrok'):
        model = apps.get_model('orders', model_name)
        model.objects.update(datum_konce=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0217_historicalsarze_popousteni_sarze_popousteni'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsarzekrok',
            name='datum_konce',
            field=models.DateField(blank=True, null=True, verbose_name='Datum konce'),
        ),
        migrations.AddField(
            model_name='sarzekrok',
            name='datum_konce',
            field=models.DateField(blank=True, null=True, verbose_name='Datum konce'),
        ),
        migrations.RunPython(doplnit_datum_konce, odebrat_datum_konce),
        migrations.AddConstraint(
            model_name='sarzekrok',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('datum_konce__isnull', True), ('konec__isnull', True)), models.Q(('datum_konce__isnull', False), ('konec__isnull', False)), _connector='OR'), name='sarzekrok_konec_a_datum_konce_spolecne'),
        ),
    ]
