# Generated by Django 5.2.17 on 2026-08-24 12:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0218_sarzekrok_datum_konce'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedna',
            name='obsah_ca',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Ca [%]'),
        ),
        migrations.AddField(
            model_name='bedna',
            name='obsah_p',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='P [%]'),
        ),
        migrations.AddField(
            model_name='bedna',
            name='obsah_zn',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Zn [%]'),
        ),
    ]
