# Generated by Django 5.2.17 on 2026-09-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0220_alter_bedna_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarze',
            options={'ordering': ['-datum_zalozeni', '-cislo_sarze'], 'permissions': (('can_move_sarze', 'Může přesouvat šarže mezi kroky'), ('can_move_sarze_limited', 'Může přesouvat šarže na vybrané typy pracovišť'), ('change_stav_sarze_operator', 'Může měnit stav šarže jako operátor'), ('change_stav_sarze_kontrolor', 'Může měnit stav šarže jako kontrolor')), 'verbose_name': 'Šarže', 'verbose_name_plural': 'šarže'},
        ),
    ]
