# Generated by Django 5.2.17 on 2026-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0221_alter_sarze_limited_move_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsarzekrok',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum začátku'),
        ),
        migrations.AlterField(
            model_name='sarzekrok',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum začátku'),
        ),
    ]
