# Generated by Django 5.2.17 on 2026-09-17 06:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0222_alter_historicalsarzekrok_datum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKontrolaBedny',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cistota', models.CharField(choices=[('--', 'Nezadáno'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Čistota')),
                ('ulozeni', models.CharField(choices=[('--', 'Nezadáno'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Uložení')),
                ('uvolneni', models.CharField(choices=[('--', 'Nerozhodnuto'), ('NE', 'Neuvolněna'), ('DZ', 'Uvolněna do dalšího zpracování'), ('KO', 'Uvolněna k odeslání')], default='--', max_length=2, verbose_name='Uvolnění')),
                ('uvolneno_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum uvolnění')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bedna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.bedna', verbose_name='Bedna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uvolnil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uvolnil')),
            ],
            options={
                'verbose_name': 'historical Kontrola bedny',
                'verbose_name_plural': 'historical kontroly beden',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KontrolaBedny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cistota', models.CharField(choices=[('--', 'Nezadáno'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Čistota')),
                ('ulozeni', models.CharField(choices=[('--', 'Nezadáno'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Uložení')),
                ('uvolneni', models.CharField(choices=[('--', 'Nerozhodnuto'), ('NE', 'Neuvolněna'), ('DZ', 'Uvolněna do dalšího zpracování'), ('KO', 'Uvolněna k odeslání')], default='--', max_length=2, verbose_name='Uvolnění')),
                ('uvolneno_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum uvolnění')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('bedna', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kontrola', to='orders.bedna', verbose_name='Bedna')),
                ('uvolnil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uvolnene_kontroly_beden', to=settings.AUTH_USER_MODEL, verbose_name='Uvolnil')),
            ],
            options={
                'verbose_name': 'Kontrola bedny',
                'verbose_name_plural': 'kontroly beden',
                'ordering': ['bedna__cislo_bedny'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMereniBedny',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('typ_zkousky', models.CharField(choices=[('ohyb', 'Ohyb'), ('krut', 'Krut'), ('prohyb_po_tz', 'Prohyb po TZ'), ('prohyb_po_kouleni', 'Prohyb po koulení'), ('prohyb_po_rovnani', 'Prohyb po rovnání'), ('tvrdost_povrchu', 'Tvrdost povrchu'), ('tvrdost_jadra', 'Tvrdost jádra')], max_length=20, verbose_name='Typ zkoušky')),
                ('hodnota', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Naměřená hodnota')),
                ('poradi', models.PositiveIntegerField(help_text='Pořadí v rámci daného typu zkoušky a kontroly bedny, počínaje 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pořadí hodnoty')),
                ('zmereno_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum měření')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zmeril', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Změřil')),
                ('kontrola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.kontrolabedny', verbose_name='Kontrola bedny')),
            ],
            options={
                'verbose_name': 'historical Měření bedny',
                'verbose_name_plural': 'historical měření beden',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MereniBedny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_zkousky', models.CharField(choices=[('ohyb', 'Ohyb'), ('krut', 'Krut'), ('prohyb_po_tz', 'Prohyb po TZ'), ('prohyb_po_kouleni', 'Prohyb po koulení'), ('prohyb_po_rovnani', 'Prohyb po rovnání'), ('tvrdost_povrchu', 'Tvrdost povrchu'), ('tvrdost_jadra', 'Tvrdost jádra')], max_length=20, verbose_name='Typ zkoušky')),
                ('hodnota', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Naměřená hodnota')),
                ('poradi', models.PositiveIntegerField(help_text='Pořadí v rámci daného typu zkoušky a kontroly bedny, počínaje 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pořadí hodnoty')),
                ('zmereno_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum měření')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('kontrola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mereni', to='orders.kontrolabedny', verbose_name='Kontrola bedny')),
                ('zmeril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mereni_beden', to=settings.AUTH_USER_MODEL, verbose_name='Změřil')),
            ],
            options={
                'verbose_name': 'Měření bedny',
                'verbose_name_plural': 'měření beden',
                'ordering': ['typ_zkousky', 'poradi'],
                'constraints': [models.UniqueConstraint(fields=('kontrola', 'typ_zkousky', 'poradi'), name='uniq_mereni_kontrola_typ_poradi'), models.CheckConstraint(condition=models.Q(('poradi__gte', 1)), name='mereni_poradi_gte_1')],
            },
        ),
    ]
