# Generated by Django 5.2.17 on 2026-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0223_kontrola_bedny_mereni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', 'Nerozhodnuto'), ('PO', 'Pozastaveno'), ('UV', 'Uvolněno')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
        migrations.AlterField(
            model_name='kontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', 'Nerozhodnuto'), ('PO', 'Pozastaveno'), ('UV', 'Uvolněno')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
    ]
