# Generated by Django 5.2.17 on 2026-09-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0224_uvolneni_vystupni_kontroly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmerenibedny',
            name='poznamka',
        ),
        migrations.RemoveField(
            model_name='merenibedny',
            name='poznamka',
        ),
    ]
