# Generated by Django 5.2.17 on 2026-09-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0225_odstranit_poznamku_mereni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbedna',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Historie Beden', 'verbose_name_plural': 'Historie Beden'},
        ),
    ]
