# Generated by Django 5.2.17 on 2026-09-29 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0226_rename_historicalbedna'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='pocet_vrutu_pro_kontrolu_prohybu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet vrutů kontrolovaných z každé bedny.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet vrutů pro kontrolu prohybu'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='pocet_vrutu_pro_kontrolu_prohybu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet vrutů kontrolovaných z každé bedny.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet vrutů pro kontrolu prohybu'),
        ),
    ]
