# Generated by Django 5.2.17 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0227_zakaznik_pocet_vrutu_pro_kontrolu_prohybu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů při opakované kontrole prohybu po nevyhovujícím prvním měření. Pokud se kontrola neopakovala, ponechte prázdné.', null=True, verbose_name='Počet křivých vrutů při druhém měření'),
        ),
        migrations.AddField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů v první kontrole prohybu. Nula znamená žádný křivý vrut; prázdné pole neprovedenou kontrolu.', null=True, verbose_name='Počet křivých vrutů při prvním měření'),
        ),
        migrations.AddField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů při opakované kontrole prohybu po nevyhovujícím prvním měření. Pokud se kontrola neopakovala, ponechte prázdné.', null=True, verbose_name='Počet křivých vrutů při druhém měření'),
        ),
        migrations.AddField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů v první kontrole prohybu. Nula znamená žádný křivý vrut; prázdné pole neprovedenou kontrolu.', null=True, verbose_name='Počet křivých vrutů při prvním měření'),
        ),
    ]
