# Generated by Django 5.2.17 on 2026-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0228_mereni_pocty_krivych_vrutu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem. Vyplňuje se společně s prvním počtem; u vyhovující bedny zůstává prázdné.', null=True, verbose_name='Počet křivých vrutů při druhém měření'),
        ),
        migrations.AlterField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem. V takovém případě vyplňte oba počty; u vyhovující bedny ponechte obě pole prázdná.', null=True, verbose_name='Počet křivých vrutů při prvním měření'),
        ),
        migrations.AlterField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem. Vyplňuje se společně s prvním počtem; u vyhovující bedny zůstává prázdné.', null=True, verbose_name='Počet křivých vrutů při druhém měření'),
        ),
        migrations.AlterField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem. V takovém případě vyplňte oba počty; u vyhovující bedny ponechte obě pole prázdná.', null=True, verbose_name='Počet křivých vrutů při prvním měření'),
        ),
    ]
