# Generated by Django 5.2.17 on 2026-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0229_upresnit_pocty_krivych_vrutu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 2. měření'),
        ),
        migrations.AlterField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 1. měření'),
        ),
        migrations.AlterField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 2. měření'),
        ),
        migrations.AlterField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 1. měření'),
        ),
    ]
