# Generated by Django 5.2.17 on 2026-09-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0230_alter_historicalmerenibedny_pocet_krivych_vrutu_druhe_mereni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
        ),
        migrations.RemoveField(
            model_name='historicalmerenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
        ),
        migrations.RemoveField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_druhe_mereni',
        ),
        migrations.RemoveField(
            model_name='merenibedny',
            name='pocet_krivych_vrutu_prvni_mereni',
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 2. měření'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 1. měření'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='pocet_krivych_vrutu_druhe_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z druhého měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 2. měření'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='pocet_krivych_vrutu_prvni_mereni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Počet křivých vrutů z prvního měření u bedny s nevyhovujícím prohybem.', null=True, verbose_name='Počet křivých 1. měření'),
        ),
    ]
