# Generated by Django 5.2.17 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0231_pocty_krivych_vrutu_do_kontroly_bedny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', 'Nerozhodnuto'), ('NE', 'Neshoda'), ('UV', 'Uvolněno'), ('UO', 'Uvolněno s odchylkou')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
        migrations.AlterField(
            model_name='kontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', 'Nerozhodnuto'), ('NE', 'Neshoda'), ('UV', 'Uvolněno'), ('UO', 'Uvolněno s odchylkou')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
    ]
