# Generated by Django 5.2.17 on 2026-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0233_autor_a_datum_zmeny_uvolneni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkontrolabedny',
            name='cistota',
            field=models.CharField(choices=[('--', '--------'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Čistota'),
        ),
        migrations.AlterField(
            model_name='historicalkontrolabedny',
            name='ulozeni',
            field=models.CharField(choices=[('--', '--------'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Uložení'),
        ),
        migrations.AlterField(
            model_name='historicalkontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', '--------'), ('NE', 'Neshoda'), ('UV', 'Uvolněno'), ('UO', 'Uvolněno s odchylkou')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
        migrations.AlterField(
            model_name='kontrolabedny',
            name='cistota',
            field=models.CharField(choices=[('--', '--------'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Čistota'),
        ),
        migrations.AlterField(
            model_name='kontrolabedny',
            name='ulozeni',
            field=models.CharField(choices=[('--', '--------'), ('OK', 'OK'), ('NOK', 'NOK')], default='--', max_length=3, verbose_name='Uložení'),
        ),
        migrations.AlterField(
            model_name='kontrolabedny',
            name='uvolneni',
            field=models.CharField(choices=[('--', '--------'), ('NE', 'Neshoda'), ('UV', 'Uvolněno'), ('UO', 'Uvolněno s odchylkou')], default='--', max_length=2, verbose_name='Uvolnění'),
        ),
    ]
