# Generated by Django 5.2.17 on 2026-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0234_popisky_nezadanych_kontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_chyba_v_procesu',
            field=models.BooleanField(default=False, verbose_name='Chyba v procesu'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_cistota',
            field=models.BooleanField(default=False, verbose_name='Čistota'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_jine',
            field=models.BooleanField(default=False, verbose_name='Jiné'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_krivost',
            field=models.BooleanField(default=False, verbose_name='Křivost'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_krut_nizky',
            field=models.BooleanField(default=False, verbose_name='Krut nízký'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_krut_vysoky',
            field=models.BooleanField(default=False, verbose_name='Krut vysoký'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_ohyb_nizky',
            field=models.BooleanField(default=False, verbose_name='Ohyb nízký'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_pomichane_vruty',
            field=models.BooleanField(default=False, verbose_name='Pomíchané vruty'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_tvrdost_jadra_nizka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost jádra nízká'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_tvrdost_jadra_vysoka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost jádra vysoká'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_tvrdost_povrchu_nizka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost povrchu nízká'),
        ),
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_tvrdost_povrchu_vysoka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost povrchu vysoká'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_chyba_v_procesu',
            field=models.BooleanField(default=False, verbose_name='Chyba v procesu'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_cistota',
            field=models.BooleanField(default=False, verbose_name='Čistota'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_jine',
            field=models.BooleanField(default=False, verbose_name='Jiné'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_krivost',
            field=models.BooleanField(default=False, verbose_name='Křivost'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_krut_nizky',
            field=models.BooleanField(default=False, verbose_name='Krut nízký'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_krut_vysoky',
            field=models.BooleanField(default=False, verbose_name='Krut vysoký'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_ohyb_nizky',
            field=models.BooleanField(default=False, verbose_name='Ohyb nízký'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_pomichane_vruty',
            field=models.BooleanField(default=False, verbose_name='Pomíchané vruty'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_tvrdost_jadra_nizka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost jádra nízká'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_tvrdost_jadra_vysoka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost jádra vysoká'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_tvrdost_povrchu_nizka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost povrchu nízká'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_tvrdost_povrchu_vysoka',
            field=models.BooleanField(default=False, verbose_name='Tvrdost povrchu vysoká'),
        ),
    ]
