# Generated by Django 5.2.17 on 2026-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0235_duvody_neshody_kontroly_bedny'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzakaznik',
            name='max_pocet_krivych_vrutu_pro_kontrolu_prohybu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nejvyšší povolený počet křivých vrutů z kontrolovaného vzorku.', null=True, verbose_name='Maximální počet křivých vrutů při kontrole prohybu'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='max_pocet_krivych_vrutu_pro_kontrolu_prohybu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nejvyšší povolený počet křivých vrutů z kontrolovaného vzorku.', null=True, verbose_name='Maximální počet křivých vrutů při kontrole prohybu'),
        ),
    ]
