# Generated by Django 5.2.17 on 2026-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0237_zakaznik_max_krivych_vrutu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkontrolabedny',
            name='neshoda_vrstva',
            field=models.BooleanField(default=False, verbose_name='Vrstva'),
        ),
        migrations.AddField(
            model_name='kontrolabedny',
            name='neshoda_vrstva',
            field=models.BooleanField(default=False, verbose_name='Vrstva'),
        ),
        migrations.AlterField(
            model_name='historicalmerenibedny',
            name='typ_zkousky',
            field=models.CharField(choices=[('ohyb', 'Ohyb'), ('krut', 'Krut'), ('prohyb_po_tz', 'Prohyb po TZ'), ('prohyb_po_kouleni', 'Prohyb po koulení'), ('prohyb_po_rovnani', 'Prohyb po rovnání'), ('tvrdost_povrchu', 'Tvrdost povrchu'), ('tvrdost_jadra', 'Tvrdost jádra'), ('vrstva', 'Vrstva')], max_length=20, verbose_name='Typ zkoušky'),
        ),
        migrations.AlterField(
            model_name='merenibedny',
            name='typ_zkousky',
            field=models.CharField(choices=[('ohyb', 'Ohyb'), ('krut', 'Krut'), ('prohyb_po_tz', 'Prohyb po TZ'), ('prohyb_po_kouleni', 'Prohyb po koulení'), ('prohyb_po_rovnani', 'Prohyb po rovnání'), ('tvrdost_povrchu', 'Tvrdost povrchu'), ('tvrdost_jadra', 'Tvrdost jádra'), ('vrstva', 'Vrstva')], max_length=20, verbose_name='Typ zkoušky'),
        ),
    ]
